using System.Collections.Immutable;
using System.Text;
using DJ.SourceGenerators.Models;

namespace DJ.SourceGenerators.Emitters;

public static class CacheDecoratorEmitter
{
    public static string Emit(ImmutableArray<ServiceInfo> services, string rootNamespace)
    {
        var sb = new StringBuilder();

        sb.AppendLine($$"""
            // <auto-generated/>
            #nullable enable

            using System;
            using System.Threading;
            using System.Threading.Tasks;
            using {{rootNamespace}}.Services;

            """);

        var byNamespace = services
            .GroupBy(s => s.Namespace)
            .OrderBy(g => g.Key);

        foreach (var group in byNamespace)
        {
            sb.AppendLine($"namespace {group.Key}");
            sb.AppendLine("{");

            foreach (var service in group.OrderBy(s => s.TypeName))
            {
                var decoratorName = $"Cached{service.TypeName}";
                var defaultDuration = service.CacheDefaultDurationSeconds;

                sb.AppendLine($"    public sealed partial class {decoratorName} : {service.FullInterfaceName}");
                sb.AppendLine("    {");
                sb.AppendLine($"        private readonly {service.FullInterfaceName} _inner;");
                sb.AppendLine("        private readonly ICacheProvider _cache;");
                sb.AppendLine($"        private const string CachePrefix = \"{service.TypeName}\";");
                sb.AppendLine();
                sb.AppendLine($"        public {decoratorName}({service.FullInterfaceName} inner, ICacheProvider cache)");
                sb.AppendLine("        {");
                sb.AppendLine("            _inner = inner ?? throw new ArgumentNullException(nameof(inner));");
                sb.AppendLine("            _cache = cache ?? throw new ArgumentNullException(nameof(cache));");
                sb.AppendLine("        }");

                foreach (var method in service.Methods)
                {
                    EmitMethod(sb, method, defaultDuration);
                }

                sb.AppendLine("    }");
                sb.AppendLine();
            }

            sb.AppendLine("}");
            sb.AppendLine();
        }

        return sb.ToString();
    }

    private static void EmitMethod(StringBuilder sb, ServiceMethodInfo method, int defaultDuration)
    {
        var parameters = string.Join(", ", method.Parameters.Select(p => $"{p.TypeName} {p.Name}"));
        var arguments = string.Join(", ", method.Parameters.Select(p => p.Name));
        var isAsync = method.IsAsync;
        var asyncKeyword = isAsync ? "async " : "";

        sb.AppendLine();
        sb.AppendLine($"        public {asyncKeyword}{method.ReturnType} {method.Name}({parameters})");
        sb.AppendLine("        {");

        if (method.CacheInvalidationTargets.Length > 0)
        {
            EmitInvalidationMethod(sb, method, arguments, isAsync);
        }
        else if (method.CacheEnabled && !method.SkipCache)
        {
            EmitCachedMethod(sb, method, arguments, defaultDuration);
        }
        else
        {
            // Pass-through
            if (isAsync)
            {
                if (method.HasReturn)
                    sb.AppendLine($"            return await _inner.{method.Name}({arguments}).ConfigureAwait(false);");
                else
                    sb.AppendLine($"            await _inner.{method.Name}({arguments}).ConfigureAwait(false);");
            }
            else
            {
                if (method.HasReturn)
                    sb.AppendLine($"            return _inner.{method.Name}({arguments});");
                else
                    sb.AppendLine($"            _inner.{method.Name}({arguments});");
            }
        }

        sb.AppendLine("        }");
    }

    private static void EmitCachedMethod(StringBuilder sb, ServiceMethodInfo method, string arguments, int defaultDuration)
    {
        var duration = method.CacheDurationSeconds ?? defaultDuration;
        var keyParams = method.Parameters.Where(p => p.IncludeInCacheKey).ToList();
        var ctParam = method.Parameters.FirstOrDefault(p => p.IsCancellationToken);
        var ctArg = ctParam != null ? ctParam.Name : "default";

        sb.AppendLine($"            var cacheKey = BuildCacheKey_{method.Name}({string.Join(", ", keyParams.Select(p => p.Name))});");

        var innerType = ExtractTaskInnerType(method.ReturnType);
        if (!string.IsNullOrEmpty(innerType) && innerType != "void")
        {
            sb.AppendLine($"            var cached = await _cache.GetAsync<{innerType}>(cacheKey, {ctArg}).ConfigureAwait(false);");
            sb.AppendLine("            if (cached is not null)");
            sb.AppendLine("                return cached;");
            sb.AppendLine();
            sb.AppendLine($"            var result = await _inner.{method.Name}({arguments}).ConfigureAwait(false);");
            sb.AppendLine($"            await _cache.SetAsync(cacheKey, result, TimeSpan.FromSeconds({duration}), {ctArg}).ConfigureAwait(false);");
            sb.AppendLine("            return result;");
        }
        else
        {
            sb.AppendLine($"            await _inner.{method.Name}({arguments}).ConfigureAwait(false);");
        }
    }

    private static void EmitInvalidationMethod(StringBuilder sb, ServiceMethodInfo method, string arguments, bool isAsync)
    {
        var ctParam = method.Parameters.FirstOrDefault(p => p.IsCancellationToken);
        var ctArg = ctParam != null ? ctParam.Name : "default";

        if (isAsync)
        {
            if (method.HasReturn)
                sb.AppendLine($"            var result = await _inner.{method.Name}({arguments}).ConfigureAwait(false);");
            else
                sb.AppendLine($"            await _inner.{method.Name}({arguments}).ConfigureAwait(false);");

            foreach (var target in method.CacheInvalidationTargets)
                sb.AppendLine($"            await _cache.RemoveByPrefixAsync($\"{{CachePrefix}}:{target}:\", {ctArg}).ConfigureAwait(false);");

            if (method.HasReturn)
                sb.AppendLine("            return result;");
        }
        else
        {
            if (method.HasReturn)
                sb.AppendLine($"            var result = _inner.{method.Name}({arguments});");
            else
                sb.AppendLine($"            _inner.{method.Name}({arguments});");

            foreach (var target in method.CacheInvalidationTargets)
                sb.AppendLine($"            _cache.RemoveByPrefixAsync($\"{{CachePrefix}}:{target}:\", default).GetAwaiter().GetResult();");

            if (method.HasReturn)
                sb.AppendLine("            return result;");
        }
    }

    private static string ExtractTaskInnerType(string returnType)
    {
        if (returnType.StartsWith("Task<") || returnType.StartsWith("System.Threading.Tasks.Task<"))
        {
            var start = returnType.IndexOf('<') + 1;
            var end = returnType.LastIndexOf('>');
            if (start > 0 && end > start)
                return returnType.Substring(start, end - start);
        }
        return string.Empty;
    }
}
