using System.Collections.Immutable;
using System.Text;
using DJ.SourceGenerators.Models;

namespace DJ.SourceGenerators.Emitters;

public static class CacheKeyEmitter
{
    public static string Emit(ImmutableArray<ServiceInfo> services)
    {
        var sb = new StringBuilder();

        sb.AppendLine("""
            // <auto-generated/>
            #nullable enable

            using System;
            using System.Text;

            """);

        var byNamespace = services
            .GroupBy(s => s.Namespace)
            .OrderBy(g => g.Key);

        foreach (var group in byNamespace)
        {
            sb.AppendLine($"namespace {group.Key}");
            sb.AppendLine("{");

            foreach (var service in group.OrderBy(s => s.TypeName))
            {
                var decoratorName = $"Cached{service.TypeName}";
                var cachedMethods = service.Methods.Where(m => m.CacheEnabled && !m.SkipCache).ToList();
                if (cachedMethods.Count == 0) continue;

                sb.AppendLine($"    public sealed partial class {decoratorName}");
                sb.AppendLine("    {");

                foreach (var method in cachedMethods)
                {
                    EmitCacheKeyMethod(sb, service, method);
                }

                sb.AppendLine("    }");
                sb.AppendLine();
            }

            sb.AppendLine("}");
            sb.AppendLine();
        }

        return sb.ToString();
    }

    private static void EmitCacheKeyMethod(StringBuilder sb, ServiceInfo service, ServiceMethodInfo method)
    {
        var keyParams = method.Parameters.Where(p => p.IncludeInCacheKey).ToList();
        var parameters = string.Join(", ", keyParams.Select(p => $"{p.TypeName} {p.Name}"));

        sb.AppendLine($"        private static string BuildCacheKey_{method.Name}({parameters})");
        sb.AppendLine("        {");

        if (keyParams.Count == 0)
        {
            sb.AppendLine($"            return $\"{{CachePrefix}}:{method.Name}\";");
        }
        else
        {
            sb.AppendLine("            var sb = new StringBuilder();");
            sb.AppendLine($"            sb.Append(CachePrefix);");
            sb.AppendLine($"            sb.Append(\":{method.Name}:\");");

            for (int i = 0; i < keyParams.Count; i++)
            {
                var param = keyParams[i];
                if (i > 0) sb.AppendLine("            sb.Append(':');");

                if (IsValueType(param.TypeName))
                    sb.AppendLine($"            sb.Append({param.Name});");
                else
                    sb.AppendLine($"            sb.Append({param.Name}?.ToString() ?? \"null\");");
            }

            sb.AppendLine("            return sb.ToString();");
        }

        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static bool IsValueType(string typeName)
    {
        return typeName switch
        {
            "int" or "Int32" or "System.Int32" => true,
            "long" or "Int64" or "System.Int64" => true,
            "short" or "Int16" or "System.Int16" => true,
            "byte" or "Byte" or "System.Byte" => true,
            "bool" or "Boolean" or "System.Boolean" => true,
            "double" or "Double" or "System.Double" => true,
            "float" or "Single" or "System.Single" => true,
            "decimal" or "Decimal" or "System.Decimal" => true,
            "char" or "Char" or "System.Char" => true,
            "Guid" or "System.Guid" => true,
            "DateTime" or "System.DateTime" => true,
            "DateTimeOffset" or "System.DateTimeOffset" => true,
            "TimeSpan" or "System.TimeSpan" => true,
            "DateOnly" or "System.DateOnly" => true,
            "TimeOnly" or "System.TimeOnly" => true,
            _ => false
        };
    }
}
