using System.Collections.Immutable;
using System.Text;
using DJ.SourceGenerators.Models;

namespace DJ.SourceGenerators.Emitters;

public static class CacheEvictionEmitter
{
    public static string Emit(ImmutableArray<ServiceInfo> services, string rootNamespace)
    {
        var sb = new StringBuilder();

        sb.AppendLine($$"""
            // <auto-generated/>
            #nullable enable

            using System;
            using System.Threading;
            using System.Threading.Tasks;
            using {{rootNamespace}}.Services;

            """);

        var byNamespace = services
            .GroupBy(s => s.Namespace)
            .OrderBy(g => g.Key);

        foreach (var group in byNamespace)
        {
            sb.AppendLine($"namespace {group.Key}");
            sb.AppendLine("{");

            foreach (var service in group.OrderBy(s => s.TypeName))
            {
                var evictionName = $"I{service.TypeName}CacheEviction";
                var evictionImplName = $"{service.TypeName}CacheEviction";

                var cachedMethods = service.Methods
                    .Where(m => m.CacheEnabled && !m.SkipCache)
                    .ToList();

                if (cachedMethods.Count == 0) continue;

                // Interface
                sb.AppendLine($"    /// <summary>");
                sb.AppendLine($"    /// Cache eviction interface for {service.TypeName}.");
                sb.AppendLine($"    /// Allows targeted eviction of cached entries by key or prefix.");
                sb.AppendLine($"    /// </summary>");
                sb.AppendLine($"    public interface {evictionName}");
                sb.AppendLine("    {");

                foreach (var method in cachedMethods)
                {
                    var keyParams = method.Parameters.Where(p => p.IncludeInCacheKey).ToList();
                    var parameters = string.Join(", ", keyParams.Select(p => $"{p.TypeName} {p.Name}"));

                    sb.AppendLine($"        /// <summary>Evict the cached result for {method.Name} with the given key.</summary>");
                    sb.AppendLine($"        Task Evict{method.Name}Async({parameters}{(keyParams.Count > 0 ? ", " : "")}CancellationToken cancellationToken = default);");
                }

                sb.AppendLine();
                sb.AppendLine("        /// <summary>Evict all cached entries for a specific method by prefix.</summary>");
                sb.AppendLine("        Task EvictByMethodAsync(string methodName, CancellationToken cancellationToken = default);");
                sb.AppendLine();
                sb.AppendLine("        /// <summary>Evict all cached entries for this service.</summary>");
                sb.AppendLine("        Task EvictAllAsync(CancellationToken cancellationToken = default);");

                sb.AppendLine("    }");
                sb.AppendLine();

                // Implementation
                sb.AppendLine($"    public sealed class {evictionImplName} : {evictionName}");
                sb.AppendLine("    {");
                sb.AppendLine("        private readonly ICacheProvider _cache;");
                sb.AppendLine($"        private const string CachePrefix = \"{service.TypeName}\";");
                sb.AppendLine();
                sb.AppendLine($"        public {evictionImplName}(ICacheProvider cache)");
                sb.AppendLine("        {");
                sb.AppendLine("            _cache = cache ?? throw new ArgumentNullException(nameof(cache));");
                sb.AppendLine("        }");

                foreach (var method in cachedMethods)
                {
                    var keyParams = method.Parameters.Where(p => p.IncludeInCacheKey).ToList();
                    var parameters = string.Join(", ", keyParams.Select(p => $"{p.TypeName} {p.Name}"));

                    sb.AppendLine();
                    sb.AppendLine($"        public async Task Evict{method.Name}Async({parameters}{(keyParams.Count > 0 ? ", " : "")}CancellationToken cancellationToken)");
                    sb.AppendLine("        {");

                    if (keyParams.Count == 0)
                    {
                        sb.AppendLine($"            await _cache.RemoveAsync($\"{{CachePrefix}}:{method.Name}\", cancellationToken).ConfigureAwait(false);");
                    }
                    else
                    {
                        // Build the exact key
                        var keyParts = new StringBuilder();
                        keyParts.Append($"$\"{{CachePrefix}}:{method.Name}:");
                        for (int i = 0; i < keyParams.Count; i++)
                        {
                            if (i > 0) keyParts.Append(":");
                            keyParts.Append($"{{{keyParams[i].Name}}}");
                        }
                        keyParts.Append("\"");
                        sb.AppendLine($"            await _cache.RemoveAsync({keyParts}, cancellationToken).ConfigureAwait(false);");
                    }

                    sb.AppendLine("        }");
                }

                sb.AppendLine();
                sb.AppendLine("        public async Task EvictByMethodAsync(string methodName, CancellationToken cancellationToken)");
                sb.AppendLine("        {");
                sb.AppendLine("            await _cache.RemoveByPrefixAsync($\"{CachePrefix}:{methodName}:\", cancellationToken).ConfigureAwait(false);");
                sb.AppendLine("        }");

                sb.AppendLine();
                sb.AppendLine("        public async Task EvictAllAsync(CancellationToken cancellationToken)");
                sb.AppendLine("        {");
                sb.AppendLine("            await _cache.RemoveByPrefixAsync($\"{CachePrefix}:\", cancellationToken).ConfigureAwait(false);");
                sb.AppendLine("        }");

                sb.AppendLine("    }");
                sb.AppendLine();
            }

            sb.AppendLine("}");
            sb.AppendLine();
        }

        return sb.ToString();
    }
}
