using System.Collections.Immutable;
using System.Text;
using DJ.SourceGenerators.Models;

namespace DJ.SourceGenerators.Emitters;

public static class CircuitBreakerDecoratorEmitter
{
    public static string Emit(ImmutableArray<ServiceInfo> services)
    {
        var sb = new StringBuilder();

        sb.AppendLine("""
            // <auto-generated/>
            #nullable enable

            using System;
            using System.Threading;
            using System.Threading.Tasks;
            using Microsoft.Extensions.Logging;

            """);

        var byNamespace = services
            .GroupBy(s => s.Namespace)
            .OrderBy(g => g.Key);

        foreach (var group in byNamespace)
        {
            sb.AppendLine($"namespace {group.Key}");
            sb.AppendLine("{");

            foreach (var service in group.OrderBy(s => s.TypeName))
            {
                var decoratorName = $"CircuitBreaker{service.TypeName}";

                sb.AppendLine($"    public sealed class {decoratorName} : {service.FullInterfaceName}");
                sb.AppendLine("    {");
                sb.AppendLine($"        private readonly {service.FullInterfaceName} _inner;");
                sb.AppendLine($"        private readonly ILogger<{decoratorName}> _logger;");
                sb.AppendLine($"        private const int FailureThreshold = {service.CircuitBreakerFailureThreshold};");
                sb.AppendLine($"        private static readonly TimeSpan ResetTimeout = TimeSpan.FromSeconds({service.CircuitBreakerResetSeconds});");
                sb.AppendLine();
                sb.AppendLine("        private int _failureCount;");
                sb.AppendLine("        private DateTime _lastFailureTime = DateTime.MinValue;");
                sb.AppendLine("        private bool _isOpen;");
                sb.AppendLine("        private readonly object _lock = new();");
                sb.AppendLine();
                sb.AppendLine($"        public {decoratorName}({service.FullInterfaceName} inner, ILogger<{decoratorName}> logger)");
                sb.AppendLine("        {");
                sb.AppendLine("            _inner = inner ?? throw new ArgumentNullException(nameof(inner));");
                sb.AppendLine("            _logger = logger ?? throw new ArgumentNullException(nameof(logger));");
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine("        private void CheckCircuit()");
                sb.AppendLine("        {");
                sb.AppendLine("            lock (_lock)");
                sb.AppendLine("            {");
                sb.AppendLine("                if (_isOpen && DateTime.UtcNow - _lastFailureTime >= ResetTimeout)");
                sb.AppendLine("                {");
                sb.AppendLine("                    _isOpen = false;");
                sb.AppendLine("                    _failureCount = 0;");
                sb.AppendLine($"                    _logger.LogInformation(\"Circuit breaker reset for {service.TypeName}\");");
                sb.AppendLine("                }");
                sb.AppendLine("                if (_isOpen)");
                sb.AppendLine("                {");
                sb.AppendLine($"                    throw new Services.CircuitBreakerOpenException(\"{service.TypeName}\");");
                sb.AppendLine("                }");
                sb.AppendLine("            }");
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine("        private void RecordSuccess()");
                sb.AppendLine("        {");
                sb.AppendLine("            lock (_lock) { _failureCount = 0; }");
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine("        private void RecordFailure()");
                sb.AppendLine("        {");
                sb.AppendLine("            lock (_lock)");
                sb.AppendLine("            {");
                sb.AppendLine("                _failureCount++;");
                sb.AppendLine("                _lastFailureTime = DateTime.UtcNow;");
                sb.AppendLine("                if (_failureCount >= FailureThreshold)");
                sb.AppendLine("                {");
                sb.AppendLine("                    _isOpen = true;");
                sb.AppendLine($"                    _logger.LogWarning(\"Circuit breaker opened for {service.TypeName} after {{FailureCount}} failures\", _failureCount);");
                sb.AppendLine("                }");
                sb.AppendLine("            }");
                sb.AppendLine("        }");

                foreach (var method in service.Methods)
                {
                    EmitMethod(sb, method);
                }

                sb.AppendLine("    }");
                sb.AppendLine();
            }

            sb.AppendLine("}");
            sb.AppendLine();
        }

        return sb.ToString();
    }

    private static void EmitMethod(StringBuilder sb, ServiceMethodInfo method)
    {
        var parameters = string.Join(", ", method.Parameters.Select(p => $"{p.TypeName} {p.Name}"));
        var arguments = string.Join(", ", method.Parameters.Select(p => p.Name));
        var asyncKeyword = method.IsAsync ? "async " : "";
        var awaitKeyword = method.IsAsync ? "await " : "";
        var configureAwait = method.IsAsync ? ".ConfigureAwait(false)" : "";

        sb.AppendLine();
        sb.AppendLine($"        public {asyncKeyword}{method.ReturnType} {method.Name}({parameters})");
        sb.AppendLine("        {");
        sb.AppendLine("            CheckCircuit();");
        sb.AppendLine("            try");
        sb.AppendLine("            {");

        if (method.HasReturn)
        {
            sb.AppendLine($"                var result = {awaitKeyword}_inner.{method.Name}({arguments}){configureAwait};");
            sb.AppendLine("                RecordSuccess();");
            sb.AppendLine("                return result;");
        }
        else
        {
            sb.AppendLine($"                {awaitKeyword}_inner.{method.Name}({arguments}){configureAwait};");
            sb.AppendLine("                RecordSuccess();");
        }

        sb.AppendLine("            }");
        sb.AppendLine("            catch (Exception)");
        sb.AppendLine("            {");
        sb.AppendLine("                RecordFailure();");
        sb.AppendLine("                throw;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
    }
}
