using System.Collections.Immutable;
using System.Text;
using DJ.SourceGenerators.Models;

namespace DJ.SourceGenerators.Emitters;

public static class DbContextEmitter
{
    public static string Emit(
        ImmutableArray<EntityInfo> entities,
        ImmutableArray<EntityConfigurationInfo> configurations,
        string rootNamespace)
    {
        var sb = new StringBuilder();

        sb.AppendLine($$"""
            // <auto-generated/>
            #nullable enable

            using Microsoft.EntityFrameworkCore;
            """);

        // Add using statements for all entity and configuration namespaces
        var namespaces = entities
            .Select(e => e.Namespace)
            .Concat(configurations.Select(c => c.Namespace))
            .Distinct()
            .OrderBy(n => n);

        foreach (var ns in namespaces)
        {
            sb.AppendLine($"using {ns};");
        }

        sb.AppendLine();
        sb.AppendLine($"namespace {rootNamespace}.Infrastructure");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Auto-generated DbContext with DbSet properties for all [Entity] classes.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public partial class ApplicationDbContext : DbContext");
        sb.AppendLine("    {");
        sb.AppendLine("        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options)");
        sb.AppendLine("        {");
        sb.AppendLine("        }");
        sb.AppendLine();

        foreach (var entity in entities.OrderBy(e => e.TypeName))
        {
            sb.AppendLine($"        public DbSet<{entity.FullTypeName}> {entity.DbSetName} {{ get; set; }}");
        }

        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Applies all discovered IEntityTypeConfiguration implementations.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        protected override void OnModelCreating(ModelBuilder modelBuilder)");
        sb.AppendLine("        {");
        foreach (var configuration in configurations.OrderBy(c => c.FullTypeName))
        {
            sb.AppendLine($"            modelBuilder.ApplyConfiguration(new {configuration.FullTypeName}());");
        }
        sb.AppendLine("        }");

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
