using System.Text;

namespace DJ.SourceGenerators.Emitters;

public static class EntityAttributeEmitter
{
    public static string Emit(string rootNamespace)
    {
        var sb = new StringBuilder();

        sb.AppendLine($$"""
            // <auto-generated/>
            #nullable enable

            using System;

            namespace {{rootNamespace}}.Entities
            {
                /// <summary>
                /// Marks a class as a database entity. The source generator will create a DbContext DbSet,
                /// IQueryable extension methods, and specification classes for this entity.
                /// </summary>
                [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
                public sealed class EntityAttribute : Attribute
                {
                }

                /// <summary>
                /// Marks a property as the primary key of the entity.
                /// If not specified, a property named "Id" or "{TypeName}Id" will be used.
                /// </summary>
                [AttributeUsage(AttributeTargets.Property, Inherited = false, AllowMultiple = false)]
                public sealed class KeyAttribute : Attribute
                {
                }

                /// <summary>
                /// Excludes a property from having extension methods and specifications generated.
                /// </summary>
                [AttributeUsage(AttributeTargets.Property, Inherited = false, AllowMultiple = false)]
                public sealed class QueryIgnoreAttribute : Attribute
                {
                }
            }
            """);

        return sb.ToString();
    }
}
