using System.Collections.Immutable;
using System.Text;
using DJ.SourceGenerators.Models;

namespace DJ.SourceGenerators.Emitters;

public static class EntityExtensionsEmitter
{
    public static string Emit(ImmutableArray<EntityInfo> entities)
    {
        var sb = new StringBuilder();

        sb.AppendLine("""
            // <auto-generated/>
            #nullable enable

            using System;
            using System.Collections.Generic;
            using System.Linq;
            using System.Linq.Expressions;
            using Microsoft.EntityFrameworkCore;

            """);

        var entitiesByNamespace = entities
            .GroupBy(e => e.Namespace)
            .OrderBy(g => g.Key);

        foreach (var namespaceGroup in entitiesByNamespace)
        {
            var extensionClassName = GetExtensionClassName(namespaceGroup.Key);

            sb.AppendLine($"namespace {namespaceGroup.Key}");
            sb.AppendLine("{");
            sb.AppendLine($"    public static class {extensionClassName}");
            sb.AppendLine("    {");

            foreach (var entity in namespaceGroup.OrderBy(e => e.TypeName))
            {
                EmitEntityExtensions(sb, entity);
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        return sb.ToString();
    }

    private static void EmitEntityExtensions(StringBuilder sb, EntityInfo entity)
    {
        sb.AppendLine($"        #region {entity.TypeName}");
        sb.AppendLine();

        var keyProperty = entity.Properties.FirstOrDefault(p => p.IsKey);

        if (keyProperty != null)
        {
            EmitWhereKeyMethod(sb, entity, keyProperty);
        }

        foreach (var property in entity.Properties.Where(p => !p.IsKey || p != keyProperty))
        {
            EmitWhereMethod(sb, entity, property);
        }

        foreach (var property in entity.Properties)
        {
            EmitOrderByMethods(sb, entity, property);
        }

        foreach (var navigation in entity.Navigations)
        {
            EmitIncludeMethod(sb, entity, navigation);
        }

        sb.AppendLine($"        #endregion");
        sb.AppendLine();
    }

    private static void EmitWhereKeyMethod(StringBuilder sb, EntityInfo entity, EntityPropertyInfo keyProperty)
    {
        var nullableAnnotation = keyProperty.IsNullable ? "?" : "";

        sb.AppendLine($"        public static IQueryable<{entity.FullTypeName}> WhereId(");
        sb.AppendLine($"            this IQueryable<{entity.FullTypeName}> query,");
        sb.AppendLine($"            {keyProperty.TypeName}{nullableAnnotation} {ToCamelCase(keyProperty.Name)})");
        sb.AppendLine($"        {{");
        sb.AppendLine($"            return query.Where(e => e.{keyProperty.Name} == {ToCamelCase(keyProperty.Name)});");
        sb.AppendLine($"        }}");
        sb.AppendLine();

        sb.AppendLine($"        public static IQueryable<{entity.FullTypeName}> WhereIdIn(");
        sb.AppendLine($"            this IQueryable<{entity.FullTypeName}> query,");
        sb.AppendLine($"            IEnumerable<{keyProperty.TypeName}> {ToCamelCase(keyProperty.Name)}s)");
        sb.AppendLine($"        {{");
        sb.AppendLine($"            return query.Where(e => {ToCamelCase(keyProperty.Name)}s.Contains(e.{keyProperty.Name}));");
        sb.AppendLine($"        }}");
        sb.AppendLine();
    }

    private static void EmitWhereMethod(StringBuilder sb, EntityInfo entity, EntityPropertyInfo property)
    {
        var nullableAnnotation = property.IsNullable ? "?" : "";
        var paramName = ToCamelCase(property.Name);

        sb.AppendLine($"        public static IQueryable<{entity.FullTypeName}> Where{property.Name}(");
        sb.AppendLine($"            this IQueryable<{entity.FullTypeName}> query,");
        sb.AppendLine($"            {property.TypeName}{nullableAnnotation} {paramName})");
        sb.AppendLine($"        {{");
        sb.AppendLine($"            return query.Where(e => e.{property.Name} == {paramName});");
        sb.AppendLine($"        }}");
        sb.AppendLine();

        if (property.IsString)
        {
            EmitStringSearchMethods(sb, entity, property);
        }

        if (property.IsNullable)
        {
            sb.AppendLine($"        public static IQueryable<{entity.FullTypeName}> WhereHas{property.Name}(");
            sb.AppendLine($"            this IQueryable<{entity.FullTypeName}> query)");
            sb.AppendLine($"        {{");
            sb.AppendLine($"            return query.Where(e => e.{property.Name} != null);");
            sb.AppendLine($"        }}");
            sb.AppendLine();

            sb.AppendLine($"        public static IQueryable<{entity.FullTypeName}> WhereHasNo{property.Name}(");
            sb.AppendLine($"            this IQueryable<{entity.FullTypeName}> query)");
            sb.AppendLine($"        {{");
            sb.AppendLine($"            return query.Where(e => e.{property.Name} == null);");
            sb.AppendLine($"        }}");
            sb.AppendLine();
        }
    }

    private static void EmitStringSearchMethods(StringBuilder sb, EntityInfo entity, EntityPropertyInfo property)
    {
        var paramName = ToCamelCase(property.Name);

        sb.AppendLine($"        public static IQueryable<{entity.FullTypeName}> Where{property.Name}Contains(");
        sb.AppendLine($"            this IQueryable<{entity.FullTypeName}> query,");
        sb.AppendLine($"            string {paramName})");
        sb.AppendLine($"        {{");
        sb.AppendLine($"            return query.Where(e => e.{property.Name} != null && e.{property.Name}.Contains({paramName}));");
        sb.AppendLine($"        }}");
        sb.AppendLine();

        sb.AppendLine($"        public static IQueryable<{entity.FullTypeName}> Where{property.Name}StartsWith(");
        sb.AppendLine($"            this IQueryable<{entity.FullTypeName}> query,");
        sb.AppendLine($"            string {paramName})");
        sb.AppendLine($"        {{");
        sb.AppendLine($"            return query.Where(e => e.{property.Name} != null && e.{property.Name}.StartsWith({paramName}));");
        sb.AppendLine($"        }}");
        sb.AppendLine();

        sb.AppendLine($"        public static IQueryable<{entity.FullTypeName}> Where{property.Name}EndsWith(");
        sb.AppendLine($"            this IQueryable<{entity.FullTypeName}> query,");
        sb.AppendLine($"            string {paramName})");
        sb.AppendLine($"        {{");
        sb.AppendLine($"            return query.Where(e => e.{property.Name} != null && e.{property.Name}.EndsWith({paramName}));");
        sb.AppendLine($"        }}");
        sb.AppendLine();
    }

    private static void EmitOrderByMethods(StringBuilder sb, EntityInfo entity, EntityPropertyInfo property)
    {
        sb.AppendLine($"        public static IOrderedQueryable<{entity.FullTypeName}> OrderBy{property.Name}(");
        sb.AppendLine($"            this IQueryable<{entity.FullTypeName}> query)");
        sb.AppendLine($"        {{");
        sb.AppendLine($"            return query.OrderBy(e => e.{property.Name});");
        sb.AppendLine($"        }}");
        sb.AppendLine();

        sb.AppendLine($"        public static IOrderedQueryable<{entity.FullTypeName}> OrderBy{property.Name}Descending(");
        sb.AppendLine($"            this IQueryable<{entity.FullTypeName}> query)");
        sb.AppendLine($"        {{");
        sb.AppendLine($"            return query.OrderByDescending(e => e.{property.Name});");
        sb.AppendLine($"        }}");
        sb.AppendLine();

        sb.AppendLine($"        public static IOrderedQueryable<{entity.FullTypeName}> ThenBy{property.Name}(");
        sb.AppendLine($"            this IOrderedQueryable<{entity.FullTypeName}> query)");
        sb.AppendLine($"        {{");
        sb.AppendLine($"            return query.ThenBy(e => e.{property.Name});");
        sb.AppendLine($"        }}");
        sb.AppendLine();

        sb.AppendLine($"        public static IOrderedQueryable<{entity.FullTypeName}> ThenBy{property.Name}Descending(");
        sb.AppendLine($"            this IOrderedQueryable<{entity.FullTypeName}> query)");
        sb.AppendLine($"        {{");
        sb.AppendLine($"            return query.ThenByDescending(e => e.{property.Name});");
        sb.AppendLine($"        }}");
        sb.AppendLine();
    }

    private static void EmitIncludeMethod(StringBuilder sb, EntityInfo entity, EntityNavigationInfo navigation)
    {
        sb.AppendLine($"        public static IQueryable<{entity.FullTypeName}> Include{navigation.Name}(");
        sb.AppendLine($"            this IQueryable<{entity.FullTypeName}> query)");
        sb.AppendLine($"        {{");
        sb.AppendLine($"            return query.Include(e => e.{navigation.Name});");
        sb.AppendLine($"        }}");
        sb.AppendLine();
    }

    private static string GetExtensionClassName(string namespaceName)
    {
        var parts = namespaceName.Split('.');
        var lastPart = parts.Length > 0 ? parts[parts.Length - 1] : "Entity";
        return $"{lastPart}QueryExtensions";
    }

    private static string ToCamelCase(string name)
    {
        if (string.IsNullOrEmpty(name))
            return name;

        return char.ToLowerInvariant(name[0]) + name.Substring(1);
    }
}
