using System.Collections.Immutable;
using System.Text;
using DJ.SourceGenerators.Models;

namespace DJ.SourceGenerators.Emitters;

public static class EnumExtensionsEmitter
{
    public static string Emit(ImmutableArray<EnumInfo> enums)
    {
        var sb = new StringBuilder();

        sb.AppendLine("""
            // <auto-generated/>
            #nullable enable

            using System;
            using System.Collections.Generic;

            """);

        var enumsByNamespace = enums
            .GroupBy(e => e.Namespace)
            .OrderBy(g => g.Key);

        foreach (var group in enumsByNamespace)
        {
            sb.AppendLine($"namespace {group.Key}");
            sb.AppendLine("{");

            foreach (var enumInfo in group.OrderBy(e => e.TypeName))
            {
                EmitEnumExtensions(sb, enumInfo);
            }

            sb.AppendLine("}");
            sb.AppendLine();
        }

        return sb.ToString();
    }

    private static void EmitEnumExtensions(StringBuilder sb, EnumInfo enumInfo)
    {
        var enumType = enumInfo.FullTypeName;
        var enumName = enumInfo.TypeName;

        sb.AppendLine($"    public static class {enumName}Extensions");
        sb.AppendLine("    {");

        // Display names dictionary
        sb.AppendLine($"        private static readonly Dictionary<{enumType}, string> _displayNames = new()");
        sb.AppendLine("        {");
        foreach (var member in enumInfo.Members)
        {
            var displayName = member.DisplayName ?? member.Name;
            sb.AppendLine($"            {{ {enumType}.{member.Name}, \"{displayName}\" }},");
        }
        sb.AppendLine("        };");
        sb.AppendLine();

        // Descriptions dictionary (only if any member has a description)
        var hasDescriptions = enumInfo.Members.Any(m => m.Description != null);
        if (hasDescriptions)
        {
            sb.AppendLine($"        private static readonly Dictionary<{enumType}, string?> _descriptions = new()");
            sb.AppendLine("        {");
            foreach (var member in enumInfo.Members)
            {
                var desc = member.Description != null ? $"\"{member.Description}\"" : "null";
                sb.AppendLine($"            {{ {enumType}.{member.Name}, {desc} }},");
            }
            sb.AppendLine("        };");
            sb.AppendLine();
        }

        // All values array
        sb.AppendLine($"        private static readonly {enumType}[] _allValues = new[]");
        sb.AppendLine("        {");
        foreach (var member in enumInfo.Members)
            sb.AppendLine($"            {enumType}.{member.Name},");
        sb.AppendLine("        };");
        sb.AppendLine();

        // ToDisplayString
        sb.AppendLine($"        public static string ToDisplayString(this {enumType} value)");
        sb.AppendLine("        {");
        sb.AppendLine("            return _displayNames.TryGetValue(value, out var name) ? name : value.ToString();");
        sb.AppendLine("        }");
        sb.AppendLine();

        // GetDescription
        if (hasDescriptions)
        {
            sb.AppendLine($"        public static string? GetDescription(this {enumType} value)");
            sb.AppendLine("        {");
            sb.AppendLine("            return _descriptions.TryGetValue(value, out var desc) ? desc : null;");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        // GetValues
        sb.AppendLine($"        public static IReadOnlyList<{enumType}> GetValues() => _allValues;");
        sb.AppendLine();

        // IsDefined
        sb.AppendLine($"        public static bool IsDefined({enumType} value) => _displayNames.ContainsKey(value);");
        sb.AppendLine();
        sb.AppendLine($"        public static bool IsDefined({enumInfo.UnderlyingType} value) => _displayNames.ContainsKey(({enumType})value);");
        sb.AppendLine();

        // TryParse
        sb.AppendLine($"        public static bool TryParse(string? value, out {enumType} result) => TryParse(value, false, out result);");
        sb.AppendLine();
        sb.AppendLine($"        public static bool TryParse(string? value, bool ignoreCase, out {enumType} result)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (string.IsNullOrEmpty(value)) { result = default; return false; }");
        sb.AppendLine("            var comparison = ignoreCase ? StringComparison.OrdinalIgnoreCase : StringComparison.Ordinal;");

        foreach (var member in enumInfo.Members)
        {
            sb.AppendLine($"            if (value.Equals(\"{member.Name}\", comparison)) {{ result = {enumType}.{member.Name}; return true; }}");
            if (member.DisplayName != null && member.DisplayName != member.Name)
                sb.AppendLine($"            if (value.Equals(\"{member.DisplayName}\", comparison)) {{ result = {enumType}.{member.Name}; return true; }}");
        }

        sb.AppendLine("            result = default; return false;");
        sb.AppendLine("        }");
        sb.AppendLine();

        // Parse
        sb.AppendLine($"        public static {enumType} Parse(string value, bool ignoreCase = false)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (TryParse(value, ignoreCase, out var result)) return result;");
        sb.AppendLine($"            throw new ArgumentException($\"'{{value}}' is not a valid {enumName} value.\", nameof(value));");
        sb.AppendLine("        }");
        sb.AppendLine();

        // Flags-specific
        if (enumInfo.IsFlags)
        {
            sb.AppendLine($"        public static bool HasFlag(this {enumType} value, {enumType} flag) => (value & flag) == flag;");
            sb.AppendLine();
            sb.AppendLine($"        public static IEnumerable<{enumType}> GetFlags(this {enumType} value)");
            sb.AppendLine("        {");
            sb.AppendLine("            foreach (var flag in _allValues)");
            sb.AppendLine("                if (flag != default && (value & flag) == flag)");
            sb.AppendLine("                    yield return flag;");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine();
    }
}
