using System.Text;

namespace DJ.SourceGenerators.Emitters;

public static class EnumAttributeEmitter
{
    public static string Emit(string rootNamespace)
    {
        var sb = new StringBuilder();

        sb.AppendLine($$"""
            // <auto-generated/>
            #nullable enable

            using System;

            namespace {{rootNamespace}}.Enums
            {
                /// <summary>
                /// Marks an enum for extension method generation.
                /// Generates: ToDisplayString, GetDescription, GetValues, IsDefined, TryParse, Parse, and [Flags] helpers.
                /// </summary>
                [AttributeUsage(AttributeTargets.Enum, Inherited = false, AllowMultiple = false)]
                public sealed class GenerateEnumExtensionsAttribute : Attribute { }

                /// <summary>
                /// Specifies a display name and optional description for an enum member.
                /// </summary>
                [AttributeUsage(AttributeTargets.Field, Inherited = false, AllowMultiple = false)]
                public sealed class DisplayAttribute : Attribute
                {
                    public DisplayAttribute(string name) { Name = name; }
                    public string Name { get; }
                    public string? Description { get; set; }
                }
            }
            """);

        return sb.ToString();
    }
}
