using System.Collections.Immutable;
using System.Text;
using DJ.SourceGenerators.Models;

namespace DJ.SourceGenerators.Emitters;

public static class RetryDecoratorEmitter
{
    public static string Emit(ImmutableArray<ServiceInfo> services)
    {
        StringBuilder sb = new StringBuilder();

        sb.AppendLine("""
            // <auto-generated/>
            #nullable enable

            using System;
            using System.Threading;
            using System.Threading.Tasks;
            using Microsoft.Extensions.Logging;

            """);

        // Deduplicate by FullTypeName
        HashSet<string> seen = new HashSet<string>();
        List<ServiceInfo> uniqueServices = services.Where(service => seen.Add(service.FullTypeName)).ToList();

        IOrderedEnumerable<IGrouping<string, ServiceInfo>> byNamespace = uniqueServices
            .GroupBy(s => s.Namespace)
            .OrderBy(g => g.Key);

        foreach (var group in byNamespace)
        {
            sb.AppendLine($"namespace {group.Key}");
            sb.AppendLine("{");

            foreach (var service in group.OrderBy(s => s.TypeName))
            {
                string decoratorName = $"Retry{service.TypeName}";

                sb.AppendLine($"    public sealed class {decoratorName} : {service.FullInterfaceName}");
                sb.AppendLine("    {");
                sb.AppendLine($"        private readonly {service.FullInterfaceName} _inner;");
                sb.AppendLine($"        private readonly ILogger<{decoratorName}> _logger;");
                sb.AppendLine($"        private const int MaxRetries = {service.RetryMaxAttempts};");
                sb.AppendLine($"        private const int InitialDelayMs = {service.RetryInitialDelayMs};");
                sb.AppendLine();
                sb.AppendLine($"        public {decoratorName}({service.FullInterfaceName} inner, ILogger<{decoratorName}> logger)");
                sb.AppendLine("        {");
                sb.AppendLine("            _inner = inner ?? throw new ArgumentNullException(nameof(inner));");
                sb.AppendLine("            _logger = logger ?? throw new ArgumentNullException(nameof(logger));");
                sb.AppendLine("        }");

                foreach (var method in service.Methods)
                {
                    EmitMethod(sb, method, service);
                }

                sb.AppendLine("    }");
                sb.AppendLine();
            }

            sb.AppendLine("}");
            sb.AppendLine();
        }

        return sb.ToString();
    }

    private static void EmitMethod(StringBuilder sb, ServiceMethodInfo method, ServiceInfo service)
    {
        string parameters = string.Join(", ", method.Parameters.Select(p => $"{p.TypeName} {p.Name}"));
        string arguments = string.Join(", ", method.Parameters.Select(p => p.Name));

        // Non-async or skip-retry: pass through
        if (!method.IsAsync || method.SkipRetry)
        {
            sb.AppendLine();
            sb.AppendLine($"        public {method.ReturnType} {method.Name}({parameters})");
            sb.AppendLine("        {");
            if (method.HasReturn)
                sb.AppendLine($"            return _inner.{method.Name}({arguments});");
            else
                sb.AppendLine($"            _inner.{method.Name}({arguments});");
            sb.AppendLine("        }");
            return;
        }

        sb.AppendLine();
        sb.AppendLine($"        public async {method.ReturnType} {method.Name}({parameters})");
        sb.AppendLine("        {");
        sb.AppendLine("            var delay = InitialDelayMs;");
        sb.AppendLine("            for (var attempt = 1; attempt <= MaxRetries; attempt++)");
        sb.AppendLine("            {");
        sb.AppendLine("                try");
        sb.AppendLine("                {");

        if (method.HasReturn)
            sb.AppendLine($"                    return await _inner.{method.Name}({arguments}).ConfigureAwait(false);");
        else
        {
            sb.AppendLine($"                    await _inner.{method.Name}({arguments}).ConfigureAwait(false);");
            sb.AppendLine("                    return;");
        }

        sb.AppendLine("                }");
        sb.AppendLine("                catch (Exception ex) when (attempt < MaxRetries)");
        sb.AppendLine("                {");
        sb.AppendLine($"                    _logger.LogWarning(ex, \"{service.TypeName}.{method.Name} failed, attempt {{Attempt}} of {{MaxRetries}}. Retrying in {{Delay}}ms\", attempt, MaxRetries, delay);");
        sb.AppendLine("                    await Task.Delay(delay).ConfigureAwait(false);");
        sb.AppendLine("                    delay *= 2;");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine();

        if (method.HasReturn)
            sb.AppendLine($"            return await _inner.{method.Name}({arguments}).ConfigureAwait(false);");
        else
            sb.AppendLine($"            await _inner.{method.Name}({arguments}).ConfigureAwait(false);");

        sb.AppendLine("        }");
    }
}
