using System.Collections.Immutable;
using System.Text;
using DJ.SourceGenerators.Models;

namespace DJ.SourceGenerators.Emitters;

public static class ServiceRegistrationEmitter
{
    public static string Emit(ImmutableArray<ServiceInfo> services, string rootNamespace)
    {
        var sb = new StringBuilder();

        sb.AppendLine("""
            // <auto-generated/>
            #nullable enable

            using System;
            using System.Linq;
            using Microsoft.Extensions.DependencyInjection;
            using Microsoft.Extensions.DependencyInjection.Extensions;
            """);

        // Deduplicate by FullTypeName
        HashSet<string> seen = [];
        List<ServiceInfo> uniqueServices = [];
        uniqueServices.AddRange(services.Where(service => seen.Add(service.FullTypeName)));

        // Add using statements for service namespaces (deduplicated with rootNamespace.Services)
        IOrderedEnumerable<string> serviceUsings = uniqueServices
            .Select(s => s.Namespace)
            .Append($"{rootNamespace}.Services")
            .Distinct()
            .OrderBy(n => n);

        foreach (string? ns in serviceUsings)
        {
            sb.AppendLine($"using {ns};");
        }

        sb.AppendLine();
        sb.AppendLine("namespace Microsoft.Extensions.DependencyInjection");
        sb.AppendLine("{");
        sb.AppendLine("    public static class GeneratedServiceExtensions");
        sb.AppendLine("    {");

        // Master registration method
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Registers all [Service] classes with their generated interfaces and all enabled decorators.");
        sb.AppendLine("        /// Decorator order (outermost to innermost): Validation → CircuitBreaker → Retry → Cache → Timing → Logging → Implementation");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static IServiceCollection AddGeneratedServices(this IServiceCollection services)");
        sb.AppendLine("        {");

        foreach (var service in uniqueServices.OrderBy(s => s.FullTypeName))
        {
            sb.AppendLine($"            services.Add{service.TypeName}();");
        }

        sb.AppendLine("            return services;");
        sb.AppendLine("        }");
        sb.AppendLine();

        // Per-service registration methods
        foreach (var service in uniqueServices.OrderBy(s => s.FullTypeName))
        {
            EmitServiceRegistration(sb, service);
        }

        // Decorate helper
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("""
                internal static class ServiceCollectionDecoratorExtensions
                {
                    public static IServiceCollection Decorate<TInterface, TDecorator>(this IServiceCollection services)
                        where TInterface : class
                        where TDecorator : class, TInterface
                    {
                        var descriptor = services.LastOrDefault(d => d.ServiceType == typeof(TInterface));
                        if (descriptor == null)
                            throw new InvalidOperationException($"Service {typeof(TInterface).Name} is not registered.");

                        services.Remove(descriptor);

                        var innerServiceType = descriptor.ImplementationType ?? descriptor.ServiceType;

                        if (descriptor.ImplementationInstance != null)
                            services.AddSingleton(innerServiceType, descriptor.ImplementationInstance);
                        else if (descriptor.ImplementationFactory != null)
                            services.Add(new ServiceDescriptor(innerServiceType, descriptor.ImplementationFactory, descriptor.Lifetime));
                        else if (descriptor.ImplementationType != null)
                            services.Add(new ServiceDescriptor(innerServiceType, descriptor.ImplementationType, descriptor.Lifetime));

                        services.Add(new ServiceDescriptor(
                            typeof(TInterface),
                            sp => ActivatorUtilities.CreateInstance<TDecorator>(sp, sp.GetRequiredService(innerServiceType)),
                            descriptor.Lifetime));

                        return services;
                    }
                }
            """);

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitServiceRegistration(StringBuilder sb, ServiceInfo service)
    {
        sb.AppendLine($"        /// <summary>");
        sb.AppendLine($"        /// Registers {service.TypeName} as {service.InterfaceName} with all enabled decorators.");
        sb.AppendLine($"        /// </summary>");
        sb.AppendLine($"        public static IServiceCollection Add{service.TypeName}(this IServiceCollection services)");
        sb.AppendLine("        {");

        // Register the concrete implementation
        sb.AppendLine($"            services.AddScoped<{service.FullInterfaceName}, {service.FullTypeName}>();");

        // Decorators are applied inside-out. The last one registered wraps everything.
        // Order: Logging (innermost) → Timing → Cache → Retry → CircuitBreaker → Validation (outermost)
        if (service.GenerateLogging)
            sb.AppendLine($"            services.Decorate<{service.FullInterfaceName}, {service.Namespace}.Logging{service.TypeName}>();");

        if (service.GenerateTiming)
            sb.AppendLine($"            services.Decorate<{service.FullInterfaceName}, {service.Namespace}.Timing{service.TypeName}>();");

        if (service.GenerateCache)
        {
            sb.AppendLine($"            services.Decorate<{service.FullInterfaceName}, {service.Namespace}.Cached{service.TypeName}>();");

            // Register cache eviction service
            var hasCachedMethods = service.Methods.Any(m => m.CacheEnabled && !m.SkipCache);
            if (hasCachedMethods)
                sb.AppendLine($"            services.AddScoped<{service.Namespace}.I{service.TypeName}CacheEviction, {service.Namespace}.{service.TypeName}CacheEviction>();");
        }

        if (service.GenerateRetry)
            sb.AppendLine($"            services.Decorate<{service.FullInterfaceName}, {service.Namespace}.Retry{service.TypeName}>();");

        if (service.GenerateCircuitBreaker)
            sb.AppendLine($"            services.Decorate<{service.FullInterfaceName}, {service.Namespace}.CircuitBreaker{service.TypeName}>();");

        if (service.GenerateValidation)
            sb.AppendLine($"            services.Decorate<{service.FullInterfaceName}, {service.Namespace}.Validating{service.TypeName}>();");

        sb.AppendLine("            return services;");
        sb.AppendLine("        }");
        sb.AppendLine();
    }
}
