using System.Text;

namespace DJ.SourceGenerators.Emitters;

public static class ServiceAttributeEmitter
{
    public static string Emit(string rootNamespace)
    {
        var sb = new StringBuilder();

        sb.AppendLine($$"""
            // <auto-generated/>
            #nullable enable

            using System;
            using System.Collections.Generic;
            using System.Threading;
            using System.Threading.Tasks;

            namespace {{rootNamespace}}.Services
            {
                /// <summary>
                /// Marks a class as a service. Generates an interface and decorator implementations
                /// for logging, timing, retry, caching, circuit breaker, and validation.
                /// </summary>
                [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
                public sealed class ServiceAttribute : Attribute
                {
                    /// <summary>Enable logging decorator. Default: true.</summary>
                    public bool Logging { get; set; } = true;

                    /// <summary>Enable timing decorator. Default: true.</summary>
                    public bool Timing { get; set; } = true;

                    /// <summary>Enable retry decorator. Default: false.</summary>
                    public bool Retry { get; set; } = false;

                    /// <summary>Enable cache decorator. Default: false.</summary>
                    public bool Cache { get; set; } = false;

                    /// <summary>Enable circuit breaker decorator. Default: false.</summary>
                    public bool CircuitBreaker { get; set; } = false;

                    /// <summary>Enable validation decorator. Default: false.</summary>
                    public bool Validation { get; set; } = false;

                    /// <summary>Max retry attempts. Default: 3.</summary>
                    public int RetryMaxAttempts { get; set; } = 3;

                    /// <summary>Initial retry delay in ms. Default: 100.</summary>
                    public int RetryInitialDelayMs { get; set; } = 100;

                    /// <summary>Default cache duration in seconds. Default: 300.</summary>
                    public int CacheDefaultDurationSeconds { get; set; } = 300;

                    /// <summary>Circuit breaker failure threshold. Default: 5.</summary>
                    public int CircuitBreakerFailureThreshold { get; set; } = 5;

                    /// <summary>Circuit breaker reset time in seconds. Default: 30.</summary>
                    public int CircuitBreakerResetSeconds { get; set; } = 30;
                }

                /// <summary>Marks a method to be cached. Only applies when Cache = true on [Service].</summary>
                [AttributeUsage(AttributeTargets.Method)]
                public sealed class CacheAttribute : Attribute
                {
                    public int DurationSeconds { get; set; }
                    public CacheAttribute(int durationSeconds = 0) { DurationSeconds = durationSeconds; }
                }

                /// <summary>Marks a method as invalidating other methods' cache entries.</summary>
                [AttributeUsage(AttributeTargets.Method)]
                public sealed class CacheInvalidateAttribute : Attribute
                {
                    public string[] MethodNames { get; }
                    public CacheInvalidateAttribute(params string[] methodNames) { MethodNames = methodNames; }
                }

                /// <summary>Excludes a parameter from cache key generation.</summary>
                [AttributeUsage(AttributeTargets.Parameter)]
                public sealed class CacheIgnoreAttribute : Attribute { }

                /// <summary>Skip logging for this method.</summary>
                [AttributeUsage(AttributeTargets.Method)]
                public sealed class NoLogAttribute : Attribute { }

                /// <summary>Skip retry for this method.</summary>
                [AttributeUsage(AttributeTargets.Method)]
                public sealed class NoRetryAttribute : Attribute { }

                /// <summary>Skip caching for this method.</summary>
                [AttributeUsage(AttributeTargets.Method)]
                public sealed class NoCacheAttribute : Attribute { }

                /// <summary>Interface for cache implementations.</summary>
                public interface ICacheProvider
                {
                    Task<T?> GetAsync<T>(string key, CancellationToken cancellationToken = default);
                    Task SetAsync<T>(string key, T value, TimeSpan expiration, CancellationToken cancellationToken = default);
                    Task RemoveAsync(string key, CancellationToken cancellationToken = default);
                    Task RemoveByPrefixAsync(string prefix, CancellationToken cancellationToken = default);
                }

                /// <summary>Interface for validating service method parameters.</summary>
                public interface IServiceValidator<in T>
                {
                    Task<ValidationResult> ValidateAsync(T instance, CancellationToken cancellationToken = default);
                }

                /// <summary>Result of a validation operation.</summary>
                public sealed class ValidationResult
                {
                    public bool IsValid { get; }
                    public IReadOnlyList<string> Errors { get; }

                    private ValidationResult(bool isValid, IReadOnlyList<string> errors)
                    {
                        IsValid = isValid;
                        Errors = errors;
                    }

                    public static ValidationResult Success() => new(true, Array.Empty<string>());
                    public static ValidationResult Failure(params string[] errors) => new(false, errors);
                    public static ValidationResult Failure(IReadOnlyList<string> errors) => new(false, errors);
                }

                /// <summary>Thrown when validation fails.</summary>
                public sealed class ValidationException : Exception
                {
                    public IReadOnlyList<string> Errors { get; }

                    public ValidationException(IReadOnlyList<string> errors)
                        : base($"Validation failed: {string.Join(", ", errors)}")
                    {
                        Errors = errors;
                    }
                }

                /// <summary>Thrown when a circuit breaker is open.</summary>
                public sealed class CircuitBreakerOpenException : Exception
                {
                    public string ServiceName { get; }

                    public CircuitBreakerOpenException(string serviceName)
                        : base($"Circuit breaker is open for {serviceName}")
                    {
                        ServiceName = serviceName;
                    }
                }
            }
            """);

        return sb.ToString();
    }
}
