using System.Collections.Immutable;
using System.Text;
using DJ.SourceGenerators.Models;

namespace DJ.SourceGenerators.Emitters;

public static class ServiceInterfaceEmitter
{
    public static string Emit(ImmutableArray<ServiceInfo> services)
    {
        StringBuilder sb = new();

        sb.AppendLine("""
            // <auto-generated/>
            #nullable enable

            using System;
            using System.Collections.Generic;
            using System.Threading;
            using System.Threading.Tasks;

            """);

        // Deduplicate by FullTypeName to prevent duplicate interfaces
        HashSet<string> seen = [];
        List<ServiceInfo> uniqueServices = services.Where(service => seen.Add(service.FullTypeName)).ToList();

        IOrderedEnumerable<IGrouping<string, ServiceInfo>> byNamespace = uniqueServices
            .GroupBy(s => s.Namespace)
            .OrderBy(g => g.Key);

        foreach (IGrouping<string, ServiceInfo>? group in byNamespace)
        {
            sb.AppendLine($"namespace {group.Key}");
            sb.AppendLine("{");

            foreach (ServiceInfo? service in group.OrderBy(s => s.TypeName))
            {
                sb.AppendLine($"    public interface {service.InterfaceName}");
                sb.AppendLine("    {");

                foreach (ServiceMethodInfo? method in service.Methods)
                {
                    string parameters = string.Join(", ", method.Parameters.Select(p => $"{p.TypeName} {p.Name}"));
                    sb.AppendLine($"        {method.ReturnType} {method.Name}({parameters});");
                }

                sb.AppendLine("    }");
                sb.AppendLine();
            }

            sb.AppendLine("}");
            sb.AppendLine();
        }

        return sb.ToString();
    }
}
