using System.Text;

namespace DJ.SourceGenerators.Emitters;

public static class SpecificationBaseEmitter
{
    public static string Emit(string rootNamespace)
    {
        var sb = new StringBuilder();

        sb.AppendLine($$"""
            // <auto-generated/>
            #nullable enable

            using System;
            using System.Collections.Generic;
            using System.Linq;
            using System.Linq.Expressions;

            namespace {{rootNamespace}}.Specifications
            {
                public interface ISpecification<T>
                {
                    Expression<Func<T, bool>> Criteria { get; }
                    IReadOnlyList<Expression<Func<T, object>>> Includes { get; }
                    IReadOnlyList<string> IncludeStrings { get; }
                    Expression<Func<T, object>>? OrderBy { get; }
                    Expression<Func<T, object>>? OrderByDescending { get; }
                    int? Take { get; }
                    int? Skip { get; }
                    bool IsPagingEnabled { get; }
                }

                public abstract class Specification<T> : ISpecification<T>
                {
                    private readonly List<Expression<Func<T, object>>> _includes = new();
                    private readonly List<string> _includeStrings = new();

                    protected Specification()
                    {
                    }

                    protected Specification(Expression<Func<T, bool>> criteria)
                    {
                        Criteria = criteria;
                    }

                    public Expression<Func<T, bool>> Criteria { get; private set; } = _ => true;
                    public IReadOnlyList<Expression<Func<T, object>>> Includes => _includes;
                    public IReadOnlyList<string> IncludeStrings => _includeStrings;
                    public Expression<Func<T, object>>? OrderBy { get; private set; }
                    public Expression<Func<T, object>>? OrderByDescending { get; private set; }
                    public int? Take { get; private set; }
                    public int? Skip { get; private set; }
                    public bool IsPagingEnabled { get; private set; }

                    protected void SetCriteria(Expression<Func<T, bool>> criteria)
                    {
                        Criteria = criteria;
                    }

                    protected void AddInclude(Expression<Func<T, object>> includeExpression)
                    {
                        _includes.Add(includeExpression);
                    }

                    protected void AddInclude(string includeString)
                    {
                        _includeStrings.Add(includeString);
                    }

                    protected void ApplyOrderBy(Expression<Func<T, object>> orderByExpression)
                    {
                        OrderBy = orderByExpression;
                    }

                    protected void ApplyOrderByDescending(Expression<Func<T, object>> orderByDescendingExpression)
                    {
                        OrderByDescending = orderByDescendingExpression;
                    }

                    protected void ApplyPaging(int skip, int take)
                    {
                        Skip = skip;
                        Take = take;
                        IsPagingEnabled = true;
                    }
                }

                public sealed class TrueSpecification<T> : Specification<T>
                {
                    public TrueSpecification() : base(x => true)
                    {
                    }
                }

                public static class SpecificationExtensions
                {
                    public static IQueryable<T> WithSpecification<T>(this IQueryable<T> query, ISpecification<T> spec) where T : class
                    {
                        query = query.Where(spec.Criteria);

                        if (spec.OrderBy != null)
                        {
                            query = query.OrderBy(spec.OrderBy);
                        }
                        else if (spec.OrderByDescending != null)
                        {
                            query = query.OrderByDescending(spec.OrderByDescending);
                        }

                        if (spec.IsPagingEnabled)
                        {
                            if (spec.Skip.HasValue)
                            {
                                query = query.Skip(spec.Skip.Value);
                            }
                            if (spec.Take.HasValue)
                            {
                                query = query.Take(spec.Take.Value);
                            }
                        }

                        return query;
                    }

                    public static ISpecification<T> And<T>(this ISpecification<T> left, ISpecification<T> right)
                    {
                        return new AndSpecification<T>(left, right);
                    }

                    public static ISpecification<T> Or<T>(this ISpecification<T> left, ISpecification<T> right)
                    {
                        return new OrSpecification<T>(left, right);
                    }

                    public static ISpecification<T> Not<T>(this ISpecification<T> spec)
                    {
                        return new NotSpecification<T>(spec);
                    }
                }

                internal sealed class AndSpecification<T> : Specification<T>
                {
                    public AndSpecification(ISpecification<T> left, ISpecification<T> right)
                    {
                        var parameter = Expression.Parameter(typeof(T), "x");

                        var leftVisitor = new ReplaceParameterVisitor(left.Criteria.Parameters[0], parameter);
                        var leftBody = leftVisitor.Visit(left.Criteria.Body);

                        var rightVisitor = new ReplaceParameterVisitor(right.Criteria.Parameters[0], parameter);
                        var rightBody = rightVisitor.Visit(right.Criteria.Body);

                        var combined = Expression.AndAlso(leftBody, rightBody);
                        SetCriteria(Expression.Lambda<Func<T, bool>>(combined, parameter));
                    }
                }

                internal sealed class OrSpecification<T> : Specification<T>
                {
                    public OrSpecification(ISpecification<T> left, ISpecification<T> right)
                    {
                        var parameter = Expression.Parameter(typeof(T), "x");

                        var leftVisitor = new ReplaceParameterVisitor(left.Criteria.Parameters[0], parameter);
                        var leftBody = leftVisitor.Visit(left.Criteria.Body);

                        var rightVisitor = new ReplaceParameterVisitor(right.Criteria.Parameters[0], parameter);
                        var rightBody = rightVisitor.Visit(right.Criteria.Body);

                        var combined = Expression.OrElse(leftBody, rightBody);
                        SetCriteria(Expression.Lambda<Func<T, bool>>(combined, parameter));
                    }
                }

                internal sealed class NotSpecification<T> : Specification<T>
                {
                    public NotSpecification(ISpecification<T> spec)
                    {
                        var parameter = Expression.Parameter(typeof(T), "x");

                        var visitor = new ReplaceParameterVisitor(spec.Criteria.Parameters[0], parameter);
                        var body = visitor.Visit(spec.Criteria.Body);

                        var negated = Expression.Not(body);
                        SetCriteria(Expression.Lambda<Func<T, bool>>(negated, parameter));
                    }
                }

                internal sealed class ReplaceParameterVisitor : ExpressionVisitor
                {
                    private readonly ParameterExpression _oldParameter;
                    private readonly ParameterExpression _newParameter;

                    public ReplaceParameterVisitor(ParameterExpression oldParameter, ParameterExpression newParameter)
                    {
                        _oldParameter = oldParameter;
                        _newParameter = newParameter;
                    }

                    protected override Expression VisitParameter(ParameterExpression node)
                    {
                        return node == _oldParameter ? _newParameter : base.VisitParameter(node);
                    }
                }
            }
            """);

        return sb.ToString();
    }
}
