using System.Collections.Immutable;
using System.Text;
using DJ.SourceGenerators.Models;

namespace DJ.SourceGenerators.Emitters;

public static class SpecificationEmitter
{
    public static string Emit(ImmutableArray<EntityInfo> entities, string rootNamespace)
    {
        var sb = new StringBuilder();

        sb.AppendLine($$"""
            // <auto-generated/>
            #nullable enable

            using System;
            using System.Collections.Generic;
            using System.Linq;
            using System.Linq.Expressions;
            using {{rootNamespace}}.Specifications;

            """);

        var entitiesByNamespace = entities
            .GroupBy(e => e.Namespace)
            .OrderBy(g => g.Key);

        foreach (var namespaceGroup in entitiesByNamespace)
        {
            sb.AppendLine($"namespace {namespaceGroup.Key}.Specifications");
            sb.AppendLine("{");

            foreach (var entity in namespaceGroup.OrderBy(e => e.TypeName))
            {
                EmitEntitySpecifications(sb, entity);
            }

            sb.AppendLine("}");
            sb.AppendLine();
        }

        return sb.ToString();
    }

    private static void EmitEntitySpecifications(StringBuilder sb, EntityInfo entity)
    {
        foreach (var prop in entity.Properties)
        {
            EmitPropertySpecifications(sb, entity, prop);
        }

        EmitSpecificationBuilder(sb, entity);
    }

    private static void EmitPropertySpecifications(StringBuilder sb, EntityInfo entity, EntityPropertyInfo prop)
    {
        var entityType = entity.FullTypeName;
        var propType = prop.TypeName;

        // Equality specification
        sb.AppendLine($"    public sealed class {entity.TypeName}By{prop.Name}Spec : Specification<{entityType}>");
        sb.AppendLine("    {");
        sb.AppendLine($"        public {entity.TypeName}By{prop.Name}Spec({propType} value)");
        sb.AppendLine("        {");
        sb.AppendLine($"            SetCriteria(x => x.{prop.Name} != null && x.{prop.Name}.Equals(value));");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();

        // String-specific specifications
        if (prop.IsString)
        {
            sb.AppendLine($"    public sealed class {entity.TypeName}{prop.Name}ContainsSpec : Specification<{entityType}>");
            sb.AppendLine("    {");
            sb.AppendLine($"        public {entity.TypeName}{prop.Name}ContainsSpec(string value, StringComparison comparison = StringComparison.OrdinalIgnoreCase)");
            sb.AppendLine("        {");
            sb.AppendLine($"            SetCriteria(x => x.{prop.Name} != null && x.{prop.Name}.Contains(value, comparison));");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();

            sb.AppendLine($"    public sealed class {entity.TypeName}{prop.Name}StartsWithSpec : Specification<{entityType}>");
            sb.AppendLine("    {");
            sb.AppendLine($"        public {entity.TypeName}{prop.Name}StartsWithSpec(string value, StringComparison comparison = StringComparison.OrdinalIgnoreCase)");
            sb.AppendLine("        {");
            sb.AppendLine($"            SetCriteria(x => x.{prop.Name} != null && x.{prop.Name}.StartsWith(value, comparison));");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();

            sb.AppendLine($"    public sealed class {entity.TypeName}{prop.Name}EndsWithSpec : Specification<{entityType}>");
            sb.AppendLine("    {");
            sb.AppendLine($"        public {entity.TypeName}{prop.Name}EndsWithSpec(string value, StringComparison comparison = StringComparison.OrdinalIgnoreCase)");
            sb.AppendLine("        {");
            sb.AppendLine($"            SetCriteria(x => x.{prop.Name} != null && x.{prop.Name}.EndsWith(value, comparison));");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        // Comparable-specific specifications
        if (prop.IsComparable && !prop.IsString)
        {
            sb.AppendLine($"    public sealed class {entity.TypeName}{prop.Name}GreaterThanSpec : Specification<{entityType}>");
            sb.AppendLine("    {");
            sb.AppendLine($"        public {entity.TypeName}{prop.Name}GreaterThanSpec({propType} value)");
            sb.AppendLine("        {");
            sb.AppendLine($"            SetCriteria(x => Comparer<{propType}>.Default.Compare(x.{prop.Name}, value) > 0);");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();

            sb.AppendLine($"    public sealed class {entity.TypeName}{prop.Name}LessThanSpec : Specification<{entityType}>");
            sb.AppendLine("    {");
            sb.AppendLine($"        public {entity.TypeName}{prop.Name}LessThanSpec({propType} value)");
            sb.AppendLine("        {");
            sb.AppendLine($"            SetCriteria(x => Comparer<{propType}>.Default.Compare(x.{prop.Name}, value) < 0);");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();

            sb.AppendLine($"    public sealed class {entity.TypeName}{prop.Name}BetweenSpec : Specification<{entityType}>");
            sb.AppendLine("    {");
            sb.AppendLine($"        public {entity.TypeName}{prop.Name}BetweenSpec({propType} min, {propType} max)");
            sb.AppendLine("        {");
            sb.AppendLine($"            SetCriteria(x => Comparer<{propType}>.Default.Compare(x.{prop.Name}, min) >= 0 && Comparer<{propType}>.Default.Compare(x.{prop.Name}, max) <= 0);");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        // Nullable-specific specifications
        if (prop.IsNullable)
        {
            sb.AppendLine($"    public sealed class {entity.TypeName}{prop.Name}IsNullSpec : Specification<{entityType}>");
            sb.AppendLine("    {");
            sb.AppendLine($"        public {entity.TypeName}{prop.Name}IsNullSpec()");
            sb.AppendLine("        {");
            sb.AppendLine($"            SetCriteria(x => x.{prop.Name} == null);");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();

            sb.AppendLine($"    public sealed class {entity.TypeName}{prop.Name}IsNotNullSpec : Specification<{entityType}>");
            sb.AppendLine("    {");
            sb.AppendLine($"        public {entity.TypeName}{prop.Name}IsNotNullSpec()");
            sb.AppendLine("        {");
            sb.AppendLine($"            SetCriteria(x => x.{prop.Name} != null);");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        // In list specification
        sb.AppendLine($"    public sealed class {entity.TypeName}{prop.Name}InSpec : Specification<{entityType}>");
        sb.AppendLine("    {");
        sb.AppendLine($"        public {entity.TypeName}{prop.Name}InSpec(IEnumerable<{propType}> values)");
        sb.AppendLine("        {");
        sb.AppendLine($"            var valueList = values.ToList();");
        sb.AppendLine($"            SetCriteria(x => x.{prop.Name} != null && valueList.Contains(x.{prop.Name}));");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine($"        public {entity.TypeName}{prop.Name}InSpec(params {propType}[] values) : this(values.AsEnumerable())");
        sb.AppendLine("        {");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitSpecificationBuilder(StringBuilder sb, EntityInfo entity)
    {
        var entityType = entity.FullTypeName;

        sb.AppendLine($"    public sealed class {entity.TypeName}SpecificationBuilder");
        sb.AppendLine("    {");
        sb.AppendLine($"        private readonly List<ISpecification<{entityType}>> _specifications = new();");
        sb.AppendLine();
        sb.AppendLine($"        public static {entity.TypeName}SpecificationBuilder Create() => new();");
        sb.AppendLine();

        foreach (var prop in entity.Properties)
        {
            EmitBuilderMethods(sb, entity, prop);
        }

        sb.AppendLine($"        public ISpecification<{entityType}> Build()");
        sb.AppendLine("        {");
        sb.AppendLine("            if (_specifications.Count == 0)");
        sb.AppendLine($"                return new TrueSpecification<{entityType}>();");
        sb.AppendLine();
        sb.AppendLine("            var result = _specifications[0];");
        sb.AppendLine("            for (int i = 1; i < _specifications.Count; i++)");
        sb.AppendLine("            {");
        sb.AppendLine("                result = result.And(_specifications[i]);");
        sb.AppendLine("            }");
        sb.AppendLine("            return result;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitBuilderMethods(StringBuilder sb, EntityInfo entity, EntityPropertyInfo prop)
    {
        var propType = prop.TypeName;

        sb.AppendLine($"        public {entity.TypeName}SpecificationBuilder Where{prop.Name}({propType} value)");
        sb.AppendLine("        {");
        sb.AppendLine($"            _specifications.Add(new {entity.TypeName}By{prop.Name}Spec(value));");
        sb.AppendLine("            return this;");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine($"        public {entity.TypeName}SpecificationBuilder Where{prop.Name}In(params {propType}[] values)");
        sb.AppendLine("        {");
        sb.AppendLine($"            _specifications.Add(new {entity.TypeName}{prop.Name}InSpec(values));");
        sb.AppendLine("            return this;");
        sb.AppendLine("        }");
        sb.AppendLine();

        if (prop.IsString)
        {
            sb.AppendLine($"        public {entity.TypeName}SpecificationBuilder Where{prop.Name}Contains(string value)");
            sb.AppendLine("        {");
            sb.AppendLine($"            _specifications.Add(new {entity.TypeName}{prop.Name}ContainsSpec(value));");
            sb.AppendLine("            return this;");
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine($"        public {entity.TypeName}SpecificationBuilder Where{prop.Name}StartsWith(string value)");
            sb.AppendLine("        {");
            sb.AppendLine($"            _specifications.Add(new {entity.TypeName}{prop.Name}StartsWithSpec(value));");
            sb.AppendLine("            return this;");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        if (prop.IsComparable && !prop.IsString)
        {
            sb.AppendLine($"        public {entity.TypeName}SpecificationBuilder Where{prop.Name}GreaterThan({propType} value)");
            sb.AppendLine("        {");
            sb.AppendLine($"            _specifications.Add(new {entity.TypeName}{prop.Name}GreaterThanSpec(value));");
            sb.AppendLine("            return this;");
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine($"        public {entity.TypeName}SpecificationBuilder Where{prop.Name}LessThan({propType} value)");
            sb.AppendLine("        {");
            sb.AppendLine($"            _specifications.Add(new {entity.TypeName}{prop.Name}LessThanSpec(value));");
            sb.AppendLine("            return this;");
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine($"        public {entity.TypeName}SpecificationBuilder Where{prop.Name}Between({propType} min, {propType} max)");
            sb.AppendLine("        {");
            sb.AppendLine($"            _specifications.Add(new {entity.TypeName}{prop.Name}BetweenSpec(min, max));");
            sb.AppendLine("            return this;");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        if (prop.IsNullable)
        {
            sb.AppendLine($"        public {entity.TypeName}SpecificationBuilder Where{prop.Name}IsNull()");
            sb.AppendLine("        {");
            sb.AppendLine($"            _specifications.Add(new {entity.TypeName}{prop.Name}IsNullSpec());");
            sb.AppendLine("            return this;");
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine($"        public {entity.TypeName}SpecificationBuilder Where{prop.Name}IsNotNull()");
            sb.AppendLine("        {");
            sb.AppendLine($"            _specifications.Add(new {entity.TypeName}{prop.Name}IsNotNullSpec());");
            sb.AppendLine("            return this;");
            sb.AppendLine("        }");
            sb.AppendLine();
        }
    }
}
