using System.Text;

namespace DJ.SourceGenerators.Emitters;

public static class StateMachineAttributeEmitter
{
    public static string Emit(string rootNamespace)
    {
        var sb = new StringBuilder();

        sb.AppendLine($$"""
            // <auto-generated/>
            #nullable enable

            using System;

            namespace {{rootNamespace}}.StateMachines
            {
                /// <summary>
                /// Marks a partial class as a state machine. The class must contain a nested enum or reference
                /// an external enum decorated with state attributes. Generates typed transitions, guards, hooks, and history.
                /// </summary>
                [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
                public sealed class StateMachineAttribute : Attribute
                {
                    /// <summary>The enum type that defines the states.</summary>
                    public Type? StateEnum { get; set; }

                    /// <summary>Enable state transition history tracking.</summary>
                    public bool TrackHistory { get; set; } = true;
                }

                /// <summary>
                /// Marks an enum member as the initial state.
                /// </summary>
                [AttributeUsage(AttributeTargets.Field, Inherited = false, AllowMultiple = false)]
                public sealed class InitialStateAttribute : Attribute { }

                /// <summary>
                /// Marks an enum member as a final/terminal state. No transitions out of this state are allowed at runtime.
                /// </summary>
                [AttributeUsage(AttributeTargets.Field, Inherited = false, AllowMultiple = false)]
                public sealed class FinalStateAttribute : Attribute { }

                /// <summary>
                /// Defines a state transition on a method. The method body becomes the transition effect.
                /// The method can be async (Task return) or sync (void return).
                /// Parameters on the method become parameters on the generated Fire method.
                /// </summary>
                [AttributeUsage(AttributeTargets.Method, Inherited = false, AllowMultiple = true)]
                public sealed class TransitionAttribute : Attribute
                {
                    public TransitionAttribute(object from, object to) { From = from; To = to; }
                    public object From { get; }
                    public object To { get; }

                    /// <summary>Name of a bool/Task&lt;bool&gt; method that guards this transition.</summary>
                    public string? Guard { get; set; }
                }

                /// <summary>
                /// Marks a method to be called when entering a specific state.
                /// </summary>
                [AttributeUsage(AttributeTargets.Method, Inherited = false, AllowMultiple = true)]
                public sealed class OnEnterAttribute : Attribute
                {
                    public OnEnterAttribute(object state) { State = state; }
                    public object State { get; }
                }

                /// <summary>
                /// Marks a method to be called when exiting a specific state.
                /// </summary>
                [AttributeUsage(AttributeTargets.Method, Inherited = false, AllowMultiple = true)]
                public sealed class OnExitAttribute : Attribute
                {
                    public OnExitAttribute(object state) { State = state; }
                    public object State { get; }
                }

                /// <summary>
                /// Represents a recorded state transition in the history.
                /// </summary>
                public sealed class StateTransitionRecord<TState> where TState : struct, Enum
                {
                    public TState From { get; init; }
                    public TState To { get; init; }
                    public string Trigger { get; init; } = "";
                    public DateTimeOffset Timestamp { get; init; }
                }

                /// <summary>
                /// Event args for state change events.
                /// </summary>
                public sealed class StateChangedEventArgs<TState> : EventArgs where TState : struct, Enum
                {
                    public TState OldState { get; init; }
                    public TState NewState { get; init; }
                    public string Trigger { get; init; } = "";
                }

                /// <summary>
                /// Event args for state changing (cancellable) events.
                /// </summary>
                public sealed class StateChangingEventArgs<TState> : EventArgs where TState : struct, Enum
                {
                    public TState CurrentState { get; init; }
                    public TState ProposedState { get; init; }
                    public string Trigger { get; init; } = "";
                    public bool Cancel { get; set; }
                }

                /// <summary>
                /// Static descriptor for a transition in the state machine graph.
                /// </summary>
                public sealed class TransitionDescriptor<TState> where TState : struct, Enum
                {
                    public string Name { get; init; } = "";
                    public TState From { get; init; }
                    public TState To { get; init; }
                    public bool HasGuard { get; init; }
                }
            }
            """);

        return sb.ToString();
    }
}
