using System.Collections.Immutable;
using System.Text;
using DJ.SourceGenerators.Models;

namespace DJ.SourceGenerators.Emitters;

public static class StateMachineEmitter
{
    public static string Emit(ImmutableArray<StateMachineInfo> machines, string rootNamespace)
    {
        var sb = new StringBuilder();

        sb.AppendLine("""
            // <auto-generated/>
            #nullable enable

            using System;
            using System.Collections.Generic;
            using System.Linq;
            using System.Threading;
            using System.Threading.Tasks;

            """);

        sb.AppendLine($"using {rootNamespace}.StateMachines;");
        sb.AppendLine();

        var machinesByNamespace = machines
            .GroupBy(m => m.Namespace)
            .OrderBy(g => g.Key);

        foreach (var group in machinesByNamespace)
        {
            sb.AppendLine($"namespace {group.Key}");
            sb.AppendLine("{");

            foreach (var machine in group.OrderBy(m => m.TypeName))
            {
                EmitStateMachine(sb, machine);
            }

            sb.AppendLine("}");
            sb.AppendLine();
        }

        return sb.ToString();
    }

    private static void EmitStateMachine(StringBuilder sb, StateMachineInfo machine)
    {
        var stateType = machine.StateEnumFullName;
        var stateShort = machine.StateEnumName;
        var initial = machine.InitialState;
        var indent = "    ";

        sb.AppendLine($"{indent}partial class {machine.TypeName}");
        sb.AppendLine($"{indent}{{");

        // ──── State property ────
        sb.AppendLine($"{indent}    private {stateType} _currentState = {stateType}.{initial};");
        sb.AppendLine($"{indent}    private readonly object _stateLock = new();");
        sb.AppendLine();
        sb.AppendLine($"{indent}    /// <summary>Current state of the state machine.</summary>");
        sb.AppendLine($"{indent}    public {stateType} CurrentState");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        get {{ lock (_stateLock) return _currentState; }}");
        sb.AppendLine($"{indent}        private set {{ _currentState = value; }}");
        sb.AppendLine($"{indent}    }}");
        sb.AppendLine();

        // ──── Events ────
        sb.AppendLine($"{indent}    /// <summary>Raised before a state transition. Set Cancel = true to prevent it.</summary>");
        sb.AppendLine($"{indent}    public event EventHandler<StateChangingEventArgs<{stateType}>>? StateChanging;");
        sb.AppendLine();
        sb.AppendLine($"{indent}    /// <summary>Raised after a state transition completes.</summary>");
        sb.AppendLine($"{indent}    public event EventHandler<StateChangedEventArgs<{stateType}>>? StateChanged;");
        sb.AppendLine();

        // ──── History ────
        if (machine.TrackHistory)
        {
            sb.AppendLine($"{indent}    private readonly List<StateTransitionRecord<{stateType}>> _stateHistory = new();");
            sb.AppendLine();
            sb.AppendLine($"{indent}    /// <summary>History of all state transitions.</summary>");
            sb.AppendLine($"{indent}    public IReadOnlyList<StateTransitionRecord<{stateType}>> StateHistory => _stateHistory;");
            sb.AppendLine();
            sb.AppendLine($"{indent}    /// <summary>Clears the transition history.</summary>");
            sb.AppendLine($"{indent}    public void ClearHistory() => _stateHistory.Clear();");
            sb.AppendLine();
        }

        // ──── IsInState ────
        sb.AppendLine($"{indent}    /// <summary>Check if the machine is in the given state.</summary>");
        sb.AppendLine($"{indent}    public bool IsInState({stateType} state) => CurrentState.Equals(state);");
        sb.AppendLine();

        // ──── Final states set ────
        var finalStates = machine.States.Where(s => s.IsFinal).ToList();
        if (finalStates.Count > 0)
        {
            sb.AppendLine($"{indent}    private static readonly HashSet<{stateType}> _finalStates = new()");
            sb.AppendLine($"{indent}    {{");
            foreach (var fs in finalStates)
                sb.AppendLine($"{indent}        {stateType}.{fs.Name},");
            sb.AppendLine($"{indent}    }};");
            sb.AppendLine();
            sb.AppendLine($"{indent}    /// <summary>Whether the machine is in a final/terminal state.</summary>");
            sb.AppendLine($"{indent}    public bool IsCompleted => _finalStates.Contains(CurrentState);");
            sb.AppendLine();
        }

        // ──── Static graph metadata ────
        EmitGraphMetadata(sb, machine, stateType, indent);

        // ──── Can* methods ────
        foreach (var transition in machine.Transitions)
        {
            EmitCanMethod(sb, machine, transition, stateType, indent);
        }

        // ──── Fire* methods ────
        foreach (var transition in machine.Transitions)
        {
            EmitFireMethod(sb, machine, transition, stateType, indent);
        }

        // ──── GetAvailableTransitions ────
        EmitGetAvailableTransitions(sb, machine, stateType, indent);

        // ──── Reset ────
        sb.AppendLine($"{indent}    /// <summary>Resets the state machine to the initial state.</summary>");
        sb.AppendLine($"{indent}    public void Reset()");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        lock (_stateLock)");
        sb.AppendLine($"{indent}        {{");
        sb.AppendLine($"{indent}            _currentState = {stateType}.{initial};");
        if (machine.TrackHistory)
            sb.AppendLine($"{indent}            _stateHistory.Clear();");
        sb.AppendLine($"{indent}        }}");
        sb.AppendLine($"{indent}    }}");
        sb.AppendLine();

        // ──── Private transition core ────
        EmitTransitionCore(sb, machine, stateType, indent);

        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
    }

    private static void EmitGraphMetadata(StringBuilder sb, StateMachineInfo machine, string stateType, string indent)
    {
        sb.AppendLine($"{indent}    /// <summary>All valid transitions in this state machine.</summary>");
        sb.AppendLine($"{indent}    public static IReadOnlyList<TransitionDescriptor<{stateType}>> AllTransitions {{ get; }} = new TransitionDescriptor<{stateType}>[]");
        sb.AppendLine($"{indent}    {{");
        foreach (var t in machine.Transitions)
        {
            var hasGuard = t.GuardMethod != null ? "true" : "false";
            sb.AppendLine($"{indent}        new() {{ Name = \"{t.Name}\", From = {stateType}.{t.From}, To = {stateType}.{t.To}, HasGuard = {hasGuard} }},");
        }
        sb.AppendLine($"{indent}    }};");
        sb.AppendLine();

        sb.AppendLine($"{indent}    /// <summary>All states in this state machine.</summary>");
        sb.AppendLine($"{indent}    public static IReadOnlyList<{stateType}> AllStates {{ get; }} = new {stateType}[]");
        sb.AppendLine($"{indent}    {{");
        foreach (var s in machine.States)
            sb.AppendLine($"{indent}        {stateType}.{s.Name},");
        sb.AppendLine($"{indent}    }};");
        sb.AppendLine();
    }

    private static void EmitCanMethod(StringBuilder sb, StateMachineInfo machine, TransitionInfo transition, string stateType, string indent)
    {
        var hasGuard = transition.GuardMethod != null;
        var isGuardAsync = hasGuard && transition.IsAsync;

        if (hasGuard && isGuardAsync)
        {
            sb.AppendLine($"{indent}    /// <summary>Whether the '{transition.Name}' transition can fire from the current state.</summary>");
            sb.AppendLine($"{indent}    public async Task<bool> Can{transition.Name}Async(CancellationToken cancellationToken = default)");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        if (!CurrentState.Equals({stateType}.{transition.From})) return false;");
            sb.AppendLine($"{indent}        return await {transition.GuardMethod}(cancellationToken).ConfigureAwait(false);");
            sb.AppendLine($"{indent}    }}");
        }
        else if (hasGuard)
        {
            sb.AppendLine($"{indent}    /// <summary>Whether the '{transition.Name}' transition can fire from the current state.</summary>");
            sb.AppendLine($"{indent}    public bool Can{transition.Name}()");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        if (!CurrentState.Equals({stateType}.{transition.From})) return false;");
            sb.AppendLine($"{indent}        return {transition.GuardMethod}();");
            sb.AppendLine($"{indent}    }}");
        }
        else
        {
            sb.AppendLine($"{indent}    /// <summary>Whether the '{transition.Name}' transition can fire from the current state.</summary>");
            sb.AppendLine($"{indent}    public bool Can{transition.Name}() => CurrentState.Equals({stateType}.{transition.From});");
        }
        sb.AppendLine();
    }

    private static void EmitFireMethod(StringBuilder sb, StateMachineInfo machine, TransitionInfo transition, string stateType, string indent)
    {
        var paramList = BuildParamList(transition.Parameters);
        var paramArgs = BuildArgList(transition.Parameters);
        var hasGuard = transition.GuardMethod != null;
        var hasEffect = transition.EffectMethod != null;

        if (transition.IsAsync)
        {
            // Async fire method
            sb.AppendLine($"{indent}    /// <summary>Fire the '{transition.Name}' transition ({transition.From} → {transition.To}).</summary>");
            sb.AppendLine($"{indent}    public async Task {transition.Name}Async({AppendCancellationToken(paramList)})");
            sb.AppendLine($"{indent}    {{");

            // Guard check
            if (hasGuard)
            {
                sb.AppendLine($"{indent}        if (!await Can{transition.Name}Async(cancellationToken).ConfigureAwait(false))");
                sb.AppendLine($"{indent}            throw new InvalidOperationException($\"Cannot fire '{transition.Name}' from state '{{CurrentState}}'. Guard rejected or invalid state.\");");
            }
            else
            {
                sb.AppendLine($"{indent}        if (!CurrentState.Equals({stateType}.{transition.From}))");
                sb.AppendLine($"{indent}            throw new InvalidOperationException($\"Cannot fire '{transition.Name}' from state '{{CurrentState}}'. Expected '{transition.From}'.\");");
            }
            sb.AppendLine();

            sb.AppendLine($"{indent}        await ExecuteTransitionAsync({stateType}.{transition.From}, {stateType}.{transition.To}, \"{transition.Name}\", async () =>");
            sb.AppendLine($"{indent}        {{");
            if (hasEffect)
            {
                var effectArgs = paramArgs.Length > 0 ? $"{paramArgs}, cancellationToken" : "cancellationToken";
                sb.AppendLine($"{indent}            await {transition.EffectMethod}({effectArgs}).ConfigureAwait(false);");
            }
            sb.AppendLine($"{indent}        }}, cancellationToken).ConfigureAwait(false);");
            sb.AppendLine($"{indent}    }}");
        }
        else
        {
            // Sync fire method
            sb.AppendLine($"{indent}    /// <summary>Fire the '{transition.Name}' transition ({transition.From} → {transition.To}).</summary>");
            sb.AppendLine($"{indent}    public void {transition.Name}({paramList})");
            sb.AppendLine($"{indent}    {{");

            if (hasGuard)
            {
                sb.AppendLine($"{indent}        if (!Can{transition.Name}())");
                sb.AppendLine($"{indent}            throw new InvalidOperationException($\"Cannot fire '{transition.Name}' from state '{{CurrentState}}'. Guard rejected or invalid state.\");");
            }
            else
            {
                sb.AppendLine($"{indent}        if (!CurrentState.Equals({stateType}.{transition.From}))");
                sb.AppendLine($"{indent}            throw new InvalidOperationException($\"Cannot fire '{transition.Name}' from state '{{CurrentState}}'. Expected '{transition.From}'.\");");
            }
            sb.AppendLine();

            sb.AppendLine($"{indent}        ExecuteTransition({stateType}.{transition.From}, {stateType}.{transition.To}, \"{transition.Name}\", () =>");
            sb.AppendLine($"{indent}        {{");
            if (hasEffect)
            {
                sb.AppendLine($"{indent}            {transition.EffectMethod}({paramArgs});");
            }
            sb.AppendLine($"{indent}        }});");
            sb.AppendLine($"{indent}    }}");
        }
        sb.AppendLine();
    }

    private static void EmitGetAvailableTransitions(StringBuilder sb, StateMachineInfo machine, string stateType, string indent)
    {
        sb.AppendLine($"{indent}    /// <summary>Get all transitions that can fire from the current state (does not evaluate guards).</summary>");
        sb.AppendLine($"{indent}    public IReadOnlyList<TransitionDescriptor<{stateType}>> GetAvailableTransitions()");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        var state = CurrentState;");
        sb.AppendLine($"{indent}        return AllTransitions.Where(t => t.From.Equals(state)).ToArray();");
        sb.AppendLine($"{indent}    }}");
        sb.AppendLine();
    }

    private static void EmitTransitionCore(StringBuilder sb, StateMachineInfo machine, string stateType, string indent)
    {
        // Sync core
        sb.AppendLine($"{indent}    private void ExecuteTransition({stateType} from, {stateType} to, string trigger, Action effect)");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        lock (_stateLock)");
        sb.AppendLine($"{indent}        {{");
        sb.AppendLine($"{indent}            var changingArgs = new StateChangingEventArgs<{stateType}> {{ CurrentState = from, ProposedState = to, Trigger = trigger }};");
        sb.AppendLine($"{indent}            StateChanging?.Invoke(this, changingArgs);");
        sb.AppendLine($"{indent}            if (changingArgs.Cancel) return;");
        sb.AppendLine();

        // OnExit hooks
        EmitSyncHooks(sb, machine.OnExitHooks, "from", indent + "            ");

        sb.AppendLine($"{indent}            effect();");
        sb.AppendLine($"{indent}            _currentState = to;");
        sb.AppendLine();

        // OnEnter hooks
        EmitSyncHooks(sb, machine.OnEnterHooks, "to", indent + "            ");

        // History
        if (machine.TrackHistory)
        {
            sb.AppendLine($"{indent}            _stateHistory.Add(new StateTransitionRecord<{stateType}> {{ From = from, To = to, Trigger = trigger, Timestamp = DateTimeOffset.UtcNow }});");
        }
        sb.AppendLine();

        sb.AppendLine($"{indent}            StateChanged?.Invoke(this, new StateChangedEventArgs<{stateType}> {{ OldState = from, NewState = to, Trigger = trigger }});");
        sb.AppendLine($"{indent}        }}");
        sb.AppendLine($"{indent}    }}");
        sb.AppendLine();

        // Async core
        sb.AppendLine($"{indent}    private async Task ExecuteTransitionAsync({stateType} from, {stateType} to, string trigger, Func<Task> effect, CancellationToken cancellationToken)");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        var changingArgs = new StateChangingEventArgs<{stateType}> {{ CurrentState = from, ProposedState = to, Trigger = trigger }};");
        sb.AppendLine($"{indent}        StateChanging?.Invoke(this, changingArgs);");
        sb.AppendLine($"{indent}        if (changingArgs.Cancel) return;");
        sb.AppendLine();

        // Async OnExit hooks
        EmitAsyncHooks(sb, machine.OnExitHooks, "from", indent + "        ");

        sb.AppendLine($"{indent}        await effect().ConfigureAwait(false);");
        sb.AppendLine();
        sb.AppendLine($"{indent}        lock (_stateLock)");
        sb.AppendLine($"{indent}        {{");
        sb.AppendLine($"{indent}            _currentState = to;");
        sb.AppendLine($"{indent}        }}");
        sb.AppendLine();

        // Async OnEnter hooks
        EmitAsyncHooks(sb, machine.OnEnterHooks, "to", indent + "        ");

        // History
        if (machine.TrackHistory)
        {
            sb.AppendLine($"{indent}        _stateHistory.Add(new StateTransitionRecord<{stateType}> {{ From = from, To = to, Trigger = trigger, Timestamp = DateTimeOffset.UtcNow }});");
        }
        sb.AppendLine();
        sb.AppendLine($"{indent}        StateChanged?.Invoke(this, new StateChangedEventArgs<{stateType}> {{ OldState = from, NewState = to, Trigger = trigger }});");
        sb.AppendLine($"{indent}    }}");
        sb.AppendLine();
    }

    private static void EmitSyncHooks(StringBuilder sb, ImmutableArray<StateHookInfo> hooks, string stateVar, string indent)
    {
        foreach (var hook in hooks)
        {
            sb.AppendLine($"{indent}if ({stateVar}.Equals({hook.StateName})) {hook.MethodName}();");
        }
    }

    private static void EmitAsyncHooks(StringBuilder sb, ImmutableArray<StateHookInfo> hooks, string stateVar, string indent)
    {
        foreach (var hook in hooks)
        {
            if (hook.IsAsync)
                sb.AppendLine($"{indent}if ({stateVar}.Equals({hook.StateName})) await {hook.MethodName}(cancellationToken).ConfigureAwait(false);");
            else
                sb.AppendLine($"{indent}if ({stateVar}.Equals({hook.StateName})) {hook.MethodName}();");
        }
    }

    private static string BuildParamList(ImmutableArray<TransitionParameterInfo> parameters)
    {
        if (parameters.Length == 0) return "";
        return string.Join(", ", parameters.Select(p => $"{p.TypeName} {p.Name}"));
    }

    private static string BuildArgList(ImmutableArray<TransitionParameterInfo> parameters)
    {
        if (parameters.Length == 0) return "";
        return string.Join(", ", parameters.Select(p => p.Name));
    }

    private static string AppendCancellationToken(string paramList)
    {
        if (string.IsNullOrEmpty(paramList))
            return "CancellationToken cancellationToken = default";
        return $"{paramList}, CancellationToken cancellationToken = default";
    }
}
