using System.Collections.Immutable;
using System.Text;
using DJ.SourceGenerators.Models;

namespace DJ.SourceGenerators.Emitters;

public static class TimingDecoratorEmitter
{
    public static string Emit(ImmutableArray<ServiceInfo> services)
    {
        var sb = new StringBuilder();

        sb.AppendLine("""
            // <auto-generated/>
            #nullable enable

            using System;
            using System.Diagnostics;
            using System.Threading;
            using System.Threading.Tasks;
            using Microsoft.Extensions.Logging;

            """);

        // Deduplicate by FullTypeName
        var seen = new HashSet<string>();
        var uniqueServices = new List<ServiceInfo>();
        foreach (var service in services)
        {
            if (seen.Add(service.FullTypeName))
                uniqueServices.Add(service);
        }

        var byNamespace = uniqueServices
            .GroupBy(s => s.Namespace)
            .OrderBy(g => g.Key);

        foreach (var group in byNamespace)
        {
            sb.AppendLine($"namespace {group.Key}");
            sb.AppendLine("{");

            foreach (var service in group.OrderBy(s => s.TypeName))
            {
                var decoratorName = $"Timing{service.TypeName}";

                sb.AppendLine($"    public sealed class {decoratorName} : {service.FullInterfaceName}");
                sb.AppendLine("    {");
                sb.AppendLine($"        private readonly {service.FullInterfaceName} _inner;");
                sb.AppendLine($"        private readonly ILogger<{decoratorName}> _logger;");
                sb.AppendLine("        private const int SlowThresholdMs = 1000;");
                sb.AppendLine();
                sb.AppendLine($"        public {decoratorName}({service.FullInterfaceName} inner, ILogger<{decoratorName}> logger)");
                sb.AppendLine("        {");
                sb.AppendLine("            _inner = inner ?? throw new ArgumentNullException(nameof(inner));");
                sb.AppendLine("            _logger = logger ?? throw new ArgumentNullException(nameof(logger));");
                sb.AppendLine("        }");

                foreach (var method in service.Methods)
                {
                    EmitMethod(sb, method, service);
                }

                sb.AppendLine("    }");
                sb.AppendLine();
            }

            sb.AppendLine("}");
            sb.AppendLine();
        }

        return sb.ToString();
    }

    private static void EmitMethod(StringBuilder sb, ServiceMethodInfo method, ServiceInfo service)
    {
        var parameters = string.Join(", ", method.Parameters.Select(p => $"{p.TypeName} {p.Name}"));
        var arguments = string.Join(", ", method.Parameters.Select(p => p.Name));
        var asyncKeyword = method.IsAsync ? "async " : "";
        var awaitKeyword = method.IsAsync ? "await " : "";
        var configureAwait = method.IsAsync ? ".ConfigureAwait(false)" : "";

        sb.AppendLine();
        sb.AppendLine($"        public {asyncKeyword}{method.ReturnType} {method.Name}({parameters})");
        sb.AppendLine("        {");
        sb.AppendLine("            var sw = Stopwatch.StartNew();");
        sb.AppendLine("            try");
        sb.AppendLine("            {");

        if (method.HasReturn)
            sb.AppendLine($"                return {awaitKeyword}_inner.{method.Name}({arguments}){configureAwait};");
        else
            sb.AppendLine($"                {awaitKeyword}_inner.{method.Name}({arguments}){configureAwait};");

        sb.AppendLine("            }");
        sb.AppendLine("            finally");
        sb.AppendLine("            {");
        sb.AppendLine("                sw.Stop();");
        sb.AppendLine("                if (sw.ElapsedMilliseconds > SlowThresholdMs)");
        sb.AppendLine($"                    _logger.LogWarning(\"{service.TypeName}.{method.Name} took {{ElapsedMs}}ms (threshold: {{ThresholdMs}}ms)\", sw.ElapsedMilliseconds, SlowThresholdMs);");
        sb.AppendLine("                else");
        sb.AppendLine($"                    _logger.LogDebug(\"{service.TypeName}.{method.Name} completed in {{ElapsedMs}}ms\", sw.ElapsedMilliseconds);");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
    }
}
