using System.Collections.Immutable;
using System.Text;
using DJ.SourceGenerators.Models;

namespace DJ.SourceGenerators.Emitters;

public static class ValidationDecoratorEmitter
{
    public static string Emit(ImmutableArray<ServiceInfo> services, string rootNamespace)
    {
        var sb = new StringBuilder();

        sb.AppendLine($$"""
            // <auto-generated/>
            #nullable enable

            using System;
            using System.Collections.Generic;
            using System.Linq;
            using System.Threading;
            using System.Threading.Tasks;
            using {{rootNamespace}}.Services;

            """);

        var byNamespace = services
            .GroupBy(s => s.Namespace)
            .OrderBy(g => g.Key);

        foreach (var group in byNamespace)
        {
            sb.AppendLine($"namespace {group.Key}");
            sb.AppendLine("{");

            foreach (var service in group.OrderBy(s => s.TypeName))
            {
                var decoratorName = $"Validating{service.TypeName}";

                sb.AppendLine($"    public sealed class {decoratorName} : {service.FullInterfaceName}");
                sb.AppendLine("    {");
                sb.AppendLine($"        private readonly {service.FullInterfaceName} _inner;");
                sb.AppendLine("        private readonly IServiceProvider _serviceProvider;");
                sb.AppendLine();
                sb.AppendLine($"        public {decoratorName}({service.FullInterfaceName} inner, IServiceProvider serviceProvider)");
                sb.AppendLine("        {");
                sb.AppendLine("            _inner = inner ?? throw new ArgumentNullException(nameof(inner));");
                sb.AppendLine("            _serviceProvider = serviceProvider ?? throw new ArgumentNullException(nameof(serviceProvider));");
                sb.AppendLine("        }");

                foreach (var method in service.Methods)
                {
                    EmitMethod(sb, method);
                }

                sb.AppendLine("    }");
                sb.AppendLine();
            }

            sb.AppendLine("}");
            sb.AppendLine();
        }

        return sb.ToString();
    }

    private static void EmitMethod(StringBuilder sb, ServiceMethodInfo method)
    {
        var parameters = string.Join(", ", method.Parameters.Select(p => $"{p.TypeName} {p.Name}"));
        var arguments = string.Join(", ", method.Parameters.Select(p => p.Name));

        // Find non-primitive, non-CancellationToken parameters that could have validators
        var validatableParams = method.Parameters
            .Where(p => !p.IsCancellationToken && !IsSimpleType(p.TypeName))
            .ToList();

        var ctParam = method.Parameters.FirstOrDefault(p => p.IsCancellationToken);
        var ctArg = ctParam != null ? ctParam.Name : "default";

        sb.AppendLine();
        sb.AppendLine($"        public async {(method.IsAsync ? method.ReturnType : (method.HasReturn ? $"Task<{method.ReturnType}>" : "Task"))} {method.Name}({parameters})");
        sb.AppendLine("        {");

        if (validatableParams.Count > 0)
        {
            sb.AppendLine("            var errors = new List<string>();");

            foreach (var param in validatableParams)
            {
                sb.AppendLine($"            var validator_{param.Name} = _serviceProvider.GetService(typeof(IServiceValidator<{param.TypeName}>)) as IServiceValidator<{param.TypeName}>;");
                sb.AppendLine($"            if (validator_{param.Name} != null)");
                sb.AppendLine("            {");
                sb.AppendLine($"                var result_{param.Name} = await validator_{param.Name}.ValidateAsync({param.Name}, {ctArg}).ConfigureAwait(false);");
                sb.AppendLine($"                if (!result_{param.Name}.IsValid)");
                sb.AppendLine($"                    errors.AddRange(result_{param.Name}.Errors);");
                sb.AppendLine("            }");
            }

            sb.AppendLine("            if (errors.Count > 0)");
            sb.AppendLine("                throw new ValidationException(errors);");
            sb.AppendLine();
        }

        var innerCall = method.IsAsync
            ? $"await _inner.{method.Name}({arguments}).ConfigureAwait(false)"
            : $"_inner.{method.Name}({arguments})";

        if (method.HasReturn)
            sb.AppendLine($"            return {innerCall};");
        else
            sb.AppendLine($"            {innerCall};");

        sb.AppendLine("        }");
    }

    private static bool IsSimpleType(string typeName)
    {
        return typeName switch
        {
            "string" or "String" or "System.String" => true,
            "int" or "Int32" or "System.Int32" => true,
            "long" or "Int64" or "System.Int64" => true,
            "short" or "Int16" or "System.Int16" => true,
            "byte" or "Byte" or "System.Byte" => true,
            "bool" or "Boolean" or "System.Boolean" => true,
            "double" or "Double" or "System.Double" => true,
            "float" or "Single" or "System.Single" => true,
            "decimal" or "Decimal" or "System.Decimal" => true,
            "char" or "Char" or "System.Char" => true,
            "Guid" or "System.Guid" => true,
            "DateTime" or "System.DateTime" => true,
            "DateTimeOffset" or "System.DateTimeOffset" => true,
            "TimeSpan" or "System.TimeSpan" => true,
            "DateOnly" or "System.DateOnly" => true,
            "TimeOnly" or "System.TimeOnly" => true,
            "CancellationToken" or "System.Threading.CancellationToken" => true,
            _ => false
        };
    }
}
