using System.Text;

namespace DJ.SourceGenerators.Emitters;

public static class ValueObjectAttributeEmitter
{
    public static string Emit(string rootNamespace)
    {
        var sb = new StringBuilder();

        sb.AppendLine($$"""
            // <auto-generated/>
            #nullable enable

            using System;

            namespace {{rootNamespace}}.ValueObjects
            {
                /// <summary>Marks a type as a value object wrapping the specified underlying type.</summary>
                [AttributeUsage(AttributeTargets.Struct | AttributeTargets.Class, Inherited = false)]
                public sealed class ValueObjectAttribute : Attribute
                {
                    public ValueObjectAttribute(Type underlyingType) { UnderlyingType = underlyingType; }
                    public Type UnderlyingType { get; }
                }

                /// <summary>Marks a type as a value object wrapping T.</summary>
                [AttributeUsage(AttributeTargets.Struct | AttributeTargets.Class, Inherited = false)]
                public sealed class ValueObjectAttribute<T> : Attribute { }

                /// <summary>Value cannot be null, empty, or default.</summary>
                [AttributeUsage(AttributeTargets.Struct | AttributeTargets.Class)]
                public sealed class NotEmptyAttribute : Attribute { }

                /// <summary>Minimum string length.</summary>
                [AttributeUsage(AttributeTargets.Struct | AttributeTargets.Class)]
                public sealed class MinLengthAttribute : Attribute
                {
                    public MinLengthAttribute(int length) { Length = length; }
                    public int Length { get; }
                }

                /// <summary>Maximum string length.</summary>
                [AttributeUsage(AttributeTargets.Struct | AttributeTargets.Class)]
                public sealed class MaxLengthAttribute : Attribute
                {
                    public MaxLengthAttribute(int length) { Length = length; }
                    public int Length { get; }
                }

                /// <summary>Regex pattern for string values.</summary>
                [AttributeUsage(AttributeTargets.Struct | AttributeTargets.Class)]
                public sealed class PatternAttribute : Attribute
                {
                    public PatternAttribute(string pattern) { Pattern = pattern; }
                    public string Pattern { get; }
                }

                /// <summary>Minimum numeric value.</summary>
                [AttributeUsage(AttributeTargets.Struct | AttributeTargets.Class)]
                public sealed class MinValueAttribute : Attribute
                {
                    public MinValueAttribute(double value) { Value = value; }
                    public double Value { get; }
                }

                /// <summary>Maximum numeric value.</summary>
                [AttributeUsage(AttributeTargets.Struct | AttributeTargets.Class)]
                public sealed class MaxValueAttribute : Attribute
                {
                    public MaxValueAttribute(double value) { Value = value; }
                    public double Value { get; }
                }

                /// <summary>Thrown when value object validation fails.</summary>
                public class ValueObjectValidationException : Exception
                {
                    public ValueObjectValidationException(string message) : base(message) { }
                    public ValueObjectValidationException(string message, Exception innerException) : base(message, innerException) { }
                }
            }
            """);

        return sb.ToString();
    }
}
