using System.Collections.Immutable;
using System.Text;
using DJ.SourceGenerators.Models;

namespace DJ.SourceGenerators.Emitters;

public static class ValueObjectEmitter
{
    public static string Emit(ImmutableArray<ValueObjectInfo> valueObjects, string rootNamespace)
    {
        var sb = new StringBuilder();

        sb.AppendLine($$"""
            // <auto-generated/>
            #nullable enable

            using System;
            using System.Collections.Generic;
            using System.Diagnostics.CodeAnalysis;
            using System.Text.RegularExpressions;
            using {{rootNamespace}}.ValueObjects;

            """);

        var byNamespace = valueObjects
            .GroupBy(v => v.Namespace)
            .OrderBy(g => g.Key);

        foreach (var group in byNamespace)
        {
            sb.AppendLine($"namespace {group.Key}");
            sb.AppendLine("{");

            foreach (var vo in group.OrderBy(v => v.TypeName))
            {
                EmitValueObject(sb, vo);
            }

            sb.AppendLine("}");
            sb.AppendLine();
        }

        return sb.ToString();
    }

    private static void EmitValueObject(StringBuilder sb, ValueObjectInfo vo)
    {
        var typeName = vo.TypeName;
        var underlyingType = vo.UnderlyingType;
        var keyword = vo.IsRecord ? (vo.IsStruct ? "record struct" : "record") : (vo.IsStruct ? "struct" : "class");
        var isString = underlyingType == "string";
        var isNumeric = IsNumericType(underlyingType);

        sb.AppendLine($"    public partial {keyword} {typeName} : IEquatable<{typeName}>, IComparable<{typeName}>, IComparable");
        sb.AppendLine("    {");

        // Value property
        sb.AppendLine($"        public {underlyingType} Value {{ get; }}");
        sb.AppendLine();

        // Private constructor
        sb.AppendLine($"        private {typeName}({underlyingType} value) {{ Value = value; }}");
        sb.AppendLine();

        // Create
        sb.AppendLine($"        public static {typeName} Create({underlyingType} value)");
        sb.AppendLine("        {");
        sb.AppendLine("            Validate(value);");
        sb.AppendLine($"            return new {typeName}(value);");
        sb.AppendLine("        }");
        sb.AppendLine();

        // TryCreate
        var outType = vo.IsStruct ? typeName : $"{typeName}?";
        var notNullAttr = vo.IsStruct ? "" : "[NotNullWhen(true)] ";
        sb.AppendLine($"        public static bool TryCreate({underlyingType} value, {notNullAttr}out {outType} result)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (IsValid(value))");
        sb.AppendLine("            {");
        sb.AppendLine($"                result = new {typeName}(value);");
        sb.AppendLine("                return true;");
        sb.AppendLine("            }");
        sb.AppendLine("            result = default;");
        sb.AppendLine("            return false;");
        sb.AppendLine("        }");
        sb.AppendLine();

        // Validate
        EmitValidateMethod(sb, vo, underlyingType, isString, isNumeric);

        // IsValid
        sb.AppendLine($"        public static bool IsValid({underlyingType} value)");
        sb.AppendLine("        {");
        sb.AppendLine("            try { Validate(value); return true; }");
        sb.AppendLine("            catch { return false; }");
        sb.AppendLine("        }");
        sb.AppendLine();

        // Implicit operators
        sb.AppendLine($"        public static implicit operator {typeName}({underlyingType} value) => Create(value);");
        sb.AppendLine($"        public static implicit operator {underlyingType}({typeName} vo) => vo.Value;");
        sb.AppendLine();

        // Equality (skip for records — they get it for free)
        if (!vo.IsRecord)
        {
            if (vo.IsStruct)
            {
                sb.AppendLine($"        public bool Equals({typeName} other) => EqualityComparer<{underlyingType}>.Default.Equals(Value, other.Value);");
                sb.AppendLine($"        public override bool Equals(object? obj) => obj is {typeName} other && Equals(other);");
            }
            else
            {
                sb.AppendLine($"        public bool Equals({typeName}? other) => other is not null && EqualityComparer<{underlyingType}>.Default.Equals(Value, other.Value);");
                sb.AppendLine($"        public override bool Equals(object? obj) => obj is {typeName} other && Equals(other);");
            }

            if (isString)
                sb.AppendLine("        public override int GetHashCode() => Value?.GetHashCode() ?? 0;");
            else
                sb.AppendLine("        public override int GetHashCode() => Value.GetHashCode();");
            sb.AppendLine();
        }

        // Comparison
        if (vo.IsStruct)
            sb.AppendLine($"        public int CompareTo({typeName} other) => Comparer<{underlyingType}>.Default.Compare(Value, other.Value);");
        else
            sb.AppendLine($"        public int CompareTo({typeName}? other) => other is null ? 1 : Comparer<{underlyingType}>.Default.Compare(Value, other.Value);");

        sb.AppendLine($"        public int CompareTo(object? obj) => obj is {typeName} other ? CompareTo(other) : throw new ArgumentException($\"Object must be of type {typeName}\");");
        sb.AppendLine();

        // Operators
        if (vo.IsStruct)
        {
            sb.AppendLine($"        public static bool operator ==({typeName} left, {typeName} right) => left.Equals(right);");
            sb.AppendLine($"        public static bool operator !=({typeName} left, {typeName} right) => !left.Equals(right);");
            sb.AppendLine($"        public static bool operator <({typeName} left, {typeName} right) => left.CompareTo(right) < 0;");
            sb.AppendLine($"        public static bool operator <=({typeName} left, {typeName} right) => left.CompareTo(right) <= 0;");
            sb.AppendLine($"        public static bool operator >({typeName} left, {typeName} right) => left.CompareTo(right) > 0;");
            sb.AppendLine($"        public static bool operator >=({typeName} left, {typeName} right) => left.CompareTo(right) >= 0;");
        }
        else
        {
            sb.AppendLine($"        public static bool operator ==({typeName}? left, {typeName}? right) => left?.Equals(right) ?? right is null;");
            sb.AppendLine($"        public static bool operator !=({typeName}? left, {typeName}? right) => !(left == right);");
            sb.AppendLine($"        public static bool operator <({typeName}? left, {typeName}? right) => left is null ? right is not null : left.CompareTo(right) < 0;");
            sb.AppendLine($"        public static bool operator <=({typeName}? left, {typeName}? right) => left is null || left.CompareTo(right) <= 0;");
            sb.AppendLine($"        public static bool operator >({typeName}? left, {typeName}? right) => left is not null && left.CompareTo(right) > 0;");
            sb.AppendLine($"        public static bool operator >=({typeName}? left, {typeName}? right) => left is null ? right is null : left.CompareTo(right) >= 0;");
        }
        sb.AppendLine();

        // ToString
        if (isString)
            sb.AppendLine("        public override string ToString() => Value ?? string.Empty;");
        else
            sb.AppendLine("        public override string ToString() => Value.ToString();");
        sb.AppendLine();

        // Struct-specific: Empty/IsEmpty
        if (vo.IsStruct)
        {
            sb.AppendLine($"        public static {typeName} Empty => default;");
            if (isString)
                sb.AppendLine("        public bool IsEmpty => string.IsNullOrEmpty(Value);");
            else
                sb.AppendLine($"        public bool IsEmpty => EqualityComparer<{underlyingType}>.Default.Equals(Value, default);");
            sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine();

        // EF Core ValueConverter
        sb.AppendLine($"    public sealed class {typeName}ValueConverter : Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter<{typeName}, {underlyingType}>");
        sb.AppendLine("    {");
        sb.AppendLine($"        public {typeName}ValueConverter() : base(v => v.Value, v => {typeName}.Create(v)) {{ }}");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitValidateMethod(StringBuilder sb, ValueObjectInfo vo, string underlyingType, bool isString, bool isNumeric)
    {
        sb.AppendLine($"        private static void Validate({underlyingType} value)");
        sb.AppendLine("        {");

        foreach (var rule in vo.ValidationRules)
        {
            switch (rule.RuleType)
            {
                case "NotEmpty" when isString:
                    sb.AppendLine($"            if (string.IsNullOrWhiteSpace(value)) throw new ValueObjectValidationException(\"{vo.TypeName} cannot be null or empty.\");");
                    break;
                case "NotEmpty":
                    sb.AppendLine($"            if (EqualityComparer<{underlyingType}>.Default.Equals(value, default)) throw new ValueObjectValidationException(\"{vo.TypeName} cannot be the default value.\");");
                    break;
                case "MinLength" when isString:
                    sb.AppendLine($"            if (value != null && value.Length < {rule.Parameter}) throw new ValueObjectValidationException(\"{vo.TypeName} must be at least {rule.Parameter} characters.\");");
                    break;
                case "MaxLength" when isString:
                    sb.AppendLine($"            if (value != null && value.Length > {rule.Parameter}) throw new ValueObjectValidationException(\"{vo.TypeName} must be at most {rule.Parameter} characters.\");");
                    break;
                case "Pattern" when isString:
                    sb.AppendLine($"            if (value != null && !Regex.IsMatch(value, @\"{rule.Parameter}\")) throw new ValueObjectValidationException(\"{vo.TypeName} does not match the required pattern.\");");
                    break;
                case "MinValue" when isNumeric:
                    sb.AppendLine($"            if (value < {rule.Parameter}) throw new ValueObjectValidationException(\"{vo.TypeName} must be at least {rule.Parameter}.\");");
                    break;
                case "MaxValue" when isNumeric:
                    sb.AppendLine($"            if (value > {rule.Parameter}) throw new ValueObjectValidationException(\"{vo.TypeName} must be at most {rule.Parameter}.\");");
                    break;
            }
        }

        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static bool IsNumericType(string typeName)
    {
        return typeName switch
        {
            "int" or "System.Int32" or "long" or "System.Int64" or
            "short" or "System.Int16" or "byte" or "System.Byte" or
            "double" or "System.Double" or "float" or "System.Single" or
            "decimal" or "System.Decimal" => true,
            _ => false
        };
    }
}
