using System.Text;

namespace DJ.SourceGenerators.Emitters;

public static class ViewModelAttributeEmitter
{
    public static string Emit(string rootNamespace)
    {
        var sb = new StringBuilder();

        sb.AppendLine($$"""
            // <auto-generated/>
            #nullable enable

            using System;
            using System.ComponentModel;
            using System.Runtime.CompilerServices;
            using System.Threading;
            using System.Threading.Tasks;
            using System.Windows.Input;

            namespace {{rootNamespace}}.ViewModels
            {
                /// <summary>
                /// Marks a partial class as a ViewModel. Generates INotifyPropertyChanged implementation,
                /// observable properties, relay commands, and busy/error state management.
                /// </summary>
                [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
                public sealed class ViewModelAttribute : Attribute { }

                /// <summary>
                /// Marks a field to generate an observable property with change notification.
                /// Field name convention: _fieldName generates PropertyName.
                /// </summary>
                [AttributeUsage(AttributeTargets.Field, Inherited = false, AllowMultiple = false)]
                public sealed class ObservableAttribute : Attribute { }

                /// <summary>
                /// Marks a method to generate an ICommand property.
                /// Method name convention: DoSomethingAsync generates DoSomethingCommand.
                /// </summary>
                [AttributeUsage(AttributeTargets.Method, Inherited = false, AllowMultiple = false)]
                public sealed class RelayCommandAttribute : Attribute
                {
                    /// <summary>Name of a bool-returning method to use as CanExecute.</summary>
                    public string? CanExecute { get; set; }
                }

                /// <summary>
                /// When placed on an [Observable] field, notifies the specified commands
                /// to re-evaluate CanExecute when the property changes.
                /// </summary>
                [AttributeUsage(AttributeTargets.Field, Inherited = false, AllowMultiple = true)]
                public sealed class NotifyCanExecuteChangedAttribute : Attribute
                {
                    public string[] CommandNames { get; }
                    public NotifyCanExecuteChangedAttribute(params string[] commandNames) { CommandNames = commandNames; }
                }

                /// <summary>
                /// When placed on an [Observable] field, also raises PropertyChanged
                /// for the specified property names when this field changes.
                /// </summary>
                [AttributeUsage(AttributeTargets.Field, Inherited = false, AllowMultiple = true)]
                public sealed class AlsoNotifyAttribute : Attribute
                {
                    public string[] PropertyNames { get; }
                    public AlsoNotifyAttribute(params string[] propertyNames) { PropertyNames = propertyNames; }
                }

                /// <summary>Synchronous relay command implementing ICommand.</summary>
                public sealed class RelayCommand : ICommand
                {
                    private readonly Action _execute;
                    private readonly Func<bool>? _canExecute;

                    public RelayCommand(Action execute, Func<bool>? canExecute = null)
                    {
                        _execute = execute ?? throw new ArgumentNullException(nameof(execute));
                        _canExecute = canExecute;
                    }

                    public event EventHandler? CanExecuteChanged;

                    public bool CanExecute(object? parameter) => _canExecute?.Invoke() ?? true;

                    public void Execute(object? parameter) => _execute();

                    public void NotifyCanExecuteChanged() => CanExecuteChanged?.Invoke(this, EventArgs.Empty);
                }

                /// <summary>Parameterized synchronous relay command.</summary>
                public sealed class RelayCommand<T> : ICommand
                {
                    private readonly Action<T?> _execute;
                    private readonly Func<T?, bool>? _canExecute;

                    public RelayCommand(Action<T?> execute, Func<T?, bool>? canExecute = null)
                    {
                        _execute = execute ?? throw new ArgumentNullException(nameof(execute));
                        _canExecute = canExecute;
                    }

                    public event EventHandler? CanExecuteChanged;

                    public bool CanExecute(object? parameter) => _canExecute?.Invoke((T?)parameter) ?? true;

                    public void Execute(object? parameter) => _execute((T?)parameter);

                    public void NotifyCanExecuteChanged() => CanExecuteChanged?.Invoke(this, EventArgs.Empty);
                }

                /// <summary>Async relay command with automatic IsBusy tracking.</summary>
                public sealed class AsyncRelayCommand : ICommand
                {
                    private readonly Func<CancellationToken, Task> _execute;
                    private readonly Func<bool>? _canExecute;
                    private readonly Action<bool>? _setBusy;
                    private readonly Action<string?>? _setError;
                    private bool _isRunning;

                    public AsyncRelayCommand(
                        Func<CancellationToken, Task> execute,
                        Func<bool>? canExecute = null,
                        Action<bool>? setBusy = null,
                        Action<string?>? setError = null)
                    {
                        _execute = execute ?? throw new ArgumentNullException(nameof(execute));
                        _canExecute = canExecute;
                        _setBusy = setBusy;
                        _setError = setError;
                    }

                    public event EventHandler? CanExecuteChanged;

                    public bool CanExecute(object? parameter) => !_isRunning && (_canExecute?.Invoke() ?? true);

                    public async void Execute(object? parameter)
                    {
                        if (_isRunning) return;
                        _isRunning = true;
                        _setBusy?.Invoke(true);
                        _setError?.Invoke(null);
                        NotifyCanExecuteChanged();
                        try
                        {
                            await _execute(CancellationToken.None).ConfigureAwait(false);
                        }
                        catch (Exception ex)
                        {
                            _setError?.Invoke(ex.Message);
                        }
                        finally
                        {
                            _isRunning = false;
                            _setBusy?.Invoke(false);
                            NotifyCanExecuteChanged();
                        }
                    }

                    public void NotifyCanExecuteChanged() => CanExecuteChanged?.Invoke(this, EventArgs.Empty);

                    public async Task ExecuteAsync(CancellationToken cancellationToken = default)
                    {
                        if (_isRunning) return;
                        _isRunning = true;
                        _setBusy?.Invoke(true);
                        _setError?.Invoke(null);
                        NotifyCanExecuteChanged();
                        try
                        {
                            await _execute(cancellationToken).ConfigureAwait(false);
                        }
                        catch (Exception ex)
                        {
                            _setError?.Invoke(ex.Message);
                        }
                        finally
                        {
                            _isRunning = false;
                            _setBusy?.Invoke(false);
                            NotifyCanExecuteChanged();
                        }
                    }
                }

                /// <summary>Parameterized async relay command with automatic IsBusy tracking.</summary>
                public sealed class AsyncRelayCommand<T> : ICommand
                {
                    private readonly Func<T?, CancellationToken, Task> _execute;
                    private readonly Func<T?, bool>? _canExecute;
                    private readonly Action<bool>? _setBusy;
                    private readonly Action<string?>? _setError;
                    private bool _isRunning;

                    public AsyncRelayCommand(
                        Func<T?, CancellationToken, Task> execute,
                        Func<T?, bool>? canExecute = null,
                        Action<bool>? setBusy = null,
                        Action<string?>? setError = null)
                    {
                        _execute = execute ?? throw new ArgumentNullException(nameof(execute));
                        _canExecute = canExecute;
                        _setBusy = setBusy;
                        _setError = setError;
                    }

                    public event EventHandler? CanExecuteChanged;

                    public bool CanExecute(object? parameter) => !_isRunning && (_canExecute?.Invoke((T?)parameter) ?? true);

                    public async void Execute(object? parameter)
                    {
                        if (_isRunning) return;
                        _isRunning = true;
                        _setBusy?.Invoke(true);
                        _setError?.Invoke(null);
                        NotifyCanExecuteChanged();
                        try
                        {
                            await _execute((T?)parameter, CancellationToken.None).ConfigureAwait(false);
                        }
                        catch (Exception ex)
                        {
                            _setError?.Invoke(ex.Message);
                        }
                        finally
                        {
                            _isRunning = false;
                            _setBusy?.Invoke(false);
                            NotifyCanExecuteChanged();
                        }
                    }

                    public void NotifyCanExecuteChanged() => CanExecuteChanged?.Invoke(this, EventArgs.Empty);

                    public async Task ExecuteAsync(T? parameter, CancellationToken cancellationToken = default)
                    {
                        if (_isRunning) return;
                        _isRunning = true;
                        _setBusy?.Invoke(true);
                        _setError?.Invoke(null);
                        NotifyCanExecuteChanged();
                        try
                        {
                            await _execute(parameter, cancellationToken).ConfigureAwait(false);
                        }
                        catch (Exception ex)
                        {
                            _setError?.Invoke(ex.Message);
                        }
                        finally
                        {
                            _isRunning = false;
                            _setBusy?.Invoke(false);
                            NotifyCanExecuteChanged();
                        }
                    }
                }
            }
            """);

        return sb.ToString();
    }
}
