using System.Collections.Immutable;
using System.Text;
using DJ.SourceGenerators.Models;

namespace DJ.SourceGenerators.Emitters;

public static class ViewModelEmitter
{
    public static string Emit(ImmutableArray<ViewModelInfo> viewModels, string rootNamespace)
    {
        var sb = new StringBuilder();

        sb.AppendLine($$"""
            // <auto-generated/>
            #nullable enable

            using System;
            using System.ComponentModel;
            using System.Runtime.CompilerServices;
            using System.Threading;
            using System.Threading.Tasks;
            using System.Windows.Input;
            using {{rootNamespace}}.ViewModels;

            """);

        var byNamespace = viewModels
            .GroupBy(vm => vm.Namespace)
            .OrderBy(g => g.Key);

        foreach (var group in byNamespace)
        {
            sb.AppendLine($"namespace {group.Key}");
            sb.AppendLine("{");

            foreach (var vm in group.OrderBy(v => v.TypeName))
            {
                EmitViewModel(sb, vm);
            }

            sb.AppendLine("}");
            sb.AppendLine();
        }

        return sb.ToString();
    }

    private static void EmitViewModel(StringBuilder sb, ViewModelInfo vm)
    {
        sb.AppendLine($"    public partial class {vm.TypeName} : INotifyPropertyChanged");
        sb.AppendLine("    {");

        // PropertyChanged event
        sb.AppendLine("        public event PropertyChangedEventHandler? PropertyChanged;");
        sb.AppendLine();

        // IsBusy property
        sb.AppendLine("        private bool _isBusy_Generated;");
        sb.AppendLine("        public bool IsBusy");
        sb.AppendLine("        {");
        sb.AppendLine("            get => _isBusy_Generated;");
        sb.AppendLine("            private set => SetProperty(ref _isBusy_Generated, value);");
        sb.AppendLine("        }");
        sb.AppendLine();

        // HasErrors property
        sb.AppendLine("        private bool _hasErrors_Generated;");
        sb.AppendLine("        public bool HasErrors");
        sb.AppendLine("        {");
        sb.AppendLine("            get => _hasErrors_Generated;");
        sb.AppendLine("            private set => SetProperty(ref _hasErrors_Generated, value);");
        sb.AppendLine("        }");
        sb.AppendLine();

        // ErrorMessage property
        sb.AppendLine("        private string? _errorMessage_Generated;");
        sb.AppendLine("        public string? ErrorMessage");
        sb.AppendLine("        {");
        sb.AppendLine("            get => _errorMessage_Generated;");
        sb.AppendLine("            private set");
        sb.AppendLine("            {");
        sb.AppendLine("                if (SetProperty(ref _errorMessage_Generated, value))");
        sb.AppendLine("                    HasErrors = value != null;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();

        // Observable properties
        foreach (var field in vm.ObservableFields)
        {
            EmitObservableProperty(sb, field);
        }

        // Relay commands
        foreach (var cmd in vm.Commands)
        {
            EmitRelayCommand(sb, cmd);
        }

        // SetProperty helper
        sb.AppendLine("        protected bool SetProperty<T>(ref T field, T value, [CallerMemberName] string? propertyName = null)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (EqualityComparer<T>.Default.Equals(field, value))");
        sb.AppendLine("                return false;");
        sb.AppendLine("            field = value;");
        sb.AppendLine("            OnPropertyChanged(propertyName);");
        sb.AppendLine("            return true;");
        sb.AppendLine("        }");
        sb.AppendLine();

        // OnPropertyChanged helper
        sb.AppendLine("        protected void OnPropertyChanged([CallerMemberName] string? propertyName = null)");
        sb.AppendLine("        {");
        sb.AppendLine("            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));");
        sb.AppendLine("        }");

        // ClearErrors helper
        sb.AppendLine();
        sb.AppendLine("        protected void ClearErrors()");
        sb.AppendLine("        {");
        sb.AppendLine("            ErrorMessage = null;");
        sb.AppendLine("        }");

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitObservableProperty(StringBuilder sb, ObservableFieldInfo field)
    {
        sb.AppendLine($"        public {field.TypeName} {field.PropertyName}");
        sb.AppendLine("        {");
        sb.AppendLine($"            get => {field.FieldName};");
        sb.AppendLine("            set");
        sb.AppendLine("            {");

        var hasNotifications = field.NotifyCanExecuteChangedFor.Length > 0 || field.AlsoNotifyFor.Length > 0;

        if (hasNotifications)
        {
            sb.AppendLine($"                if (SetProperty(ref {field.FieldName}, value))");
            sb.AppendLine("                {");

            foreach (var cmdName in field.NotifyCanExecuteChangedFor)
            {
                sb.AppendLine($"                    {cmdName}.NotifyCanExecuteChanged();");
            }

            foreach (var propName in field.AlsoNotifyFor)
            {
                sb.AppendLine($"                    OnPropertyChanged(nameof({propName}));");
            }

            sb.AppendLine("                }");
        }
        else
        {
            sb.AppendLine($"                SetProperty(ref {field.FieldName}, value);");
        }

        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void EmitRelayCommand(StringBuilder sb, RelayCommandInfo cmd)
    {
        if (cmd.IsAsync)
        {
            EmitAsyncRelayCommand(sb, cmd);
        }
        else
        {
            EmitSyncRelayCommand(sb, cmd);
        }
    }

    private static void EmitSyncRelayCommand(StringBuilder sb, RelayCommandInfo cmd)
    {
        if (cmd.HasParameter && cmd.ParameterTypeName != null)
        {
            var type = cmd.ParameterTypeName;
            sb.AppendLine($"        private RelayCommand<{type}>? _{ToCamelCase(cmd.CommandName)};");
            sb.AppendLine($"        public RelayCommand<{type}> {cmd.CommandName} => _{ToCamelCase(cmd.CommandName)} ??= new RelayCommand<{type}>(");
            sb.AppendLine($"            {cmd.MethodName}{(cmd.CanExecuteMethodName != null ? $", {cmd.CanExecuteMethodName}" : "")});");
        }
        else
        {
            sb.AppendLine($"        private RelayCommand? _{ToCamelCase(cmd.CommandName)};");
            sb.AppendLine($"        public RelayCommand {cmd.CommandName} => _{ToCamelCase(cmd.CommandName)} ??= new RelayCommand(");
            sb.AppendLine($"            {cmd.MethodName}{(cmd.CanExecuteMethodName != null ? $", {cmd.CanExecuteMethodName}" : "")});");
        }
        sb.AppendLine();
    }

    private static void EmitAsyncRelayCommand(StringBuilder sb, RelayCommandInfo cmd)
    {
        if (cmd.HasParameter && cmd.ParameterTypeName != null)
        {
            var type = cmd.ParameterTypeName;

            // Build the delegate that adapts to the method signature
            string delegateExpr;
            if (cmd.HasCancellationToken)
                delegateExpr = $"(p, ct) => {cmd.MethodName}(p, ct)";
            else
                delegateExpr = $"(p, ct) => {cmd.MethodName}(p)";

            sb.AppendLine($"        private AsyncRelayCommand<{type}>? _{ToCamelCase(cmd.CommandName)};");
            sb.AppendLine($"        public AsyncRelayCommand<{type}> {cmd.CommandName} => _{ToCamelCase(cmd.CommandName)} ??= new AsyncRelayCommand<{type}>(");
            sb.AppendLine($"            {delegateExpr},");
            sb.AppendLine($"            {(cmd.CanExecuteMethodName != null ? cmd.CanExecuteMethodName : "null")},");
            sb.AppendLine($"            value => IsBusy = value,");
            sb.AppendLine($"            value => ErrorMessage = value);");
        }
        else
        {
            // Build the delegate that adapts to the method signature
            string delegateExpr;
            if (cmd.HasCancellationToken)
                delegateExpr = $"ct => {cmd.MethodName}(ct)";
            else
                delegateExpr = $"ct => {cmd.MethodName}()";

            sb.AppendLine($"        private AsyncRelayCommand? _{ToCamelCase(cmd.CommandName)};");
            sb.AppendLine($"        public AsyncRelayCommand {cmd.CommandName} => _{ToCamelCase(cmd.CommandName)} ??= new AsyncRelayCommand(");
            sb.AppendLine($"            {delegateExpr},");
            sb.AppendLine($"            {(cmd.CanExecuteMethodName != null ? cmd.CanExecuteMethodName : "null")},");
            sb.AppendLine($"            value => IsBusy = value,");
            sb.AppendLine($"            value => ErrorMessage = value);");
        }
        sb.AppendLine();
    }

    private static string ToCamelCase(string name)
    {
        if (string.IsNullOrEmpty(name)) return name;
        return char.ToLowerInvariant(name[0]) + name.Substring(1);
    }
}
