using System;
using System.Collections.Immutable;
using System.Linq;
using DJ.SourceGenerators.Emitters;
using DJ.SourceGenerators.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace DJ.SourceGenerators;

internal sealed class ViewModelValidationResult
{
    public ViewModelInfo? Info { get; init; }
    public ImmutableArray<Diagnostic> Diagnostics { get; init; }
}

[Generator]
public class ViewModelGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var rootNamespaceProvider = context.AnalyzerConfigOptionsProvider
            .Select(static (options, _) =>
            {
                options.GlobalOptions.TryGetValue("build_property.RootNamespace", out var ns);
                return ns ?? "Generated";
            });

        context.RegisterSourceOutput(rootNamespaceProvider, static (spc, rootNamespace) =>
        {
            spc.AddSource("ViewModelAttributes.g.cs", ViewModelAttributeEmitter.Emit(rootNamespace));
        });

        var viewModelProvider = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax cds && cds.AttributeLists.Count > 0,
                transform: static (ctx, _) => ExtractViewModelInfoWithValidation(ctx));

        var collectedViewModels = viewModelProvider.Collect();
        var combined = collectedViewModels.Combine(rootNamespaceProvider);

        context.RegisterSourceOutput(combined, static (spc, tuple) =>
        {
            var (results, rootNamespace) = tuple;
            
            // Report all diagnostics
            foreach (var result in results)
            {
                foreach (var diag in result.Diagnostics)
                {
                    spc.ReportDiagnostic(diag);
                }
            }

            // Generate code only for valid ViewModels
            var vmList = results
                .Where(r => r.Info is not null)
                .Select(r => r.Info!)
                .Distinct()
                .ToImmutableArray();

            if (vmList.Length == 0)
                return;

            spc.AddSource("ViewModels.g.cs", ViewModelEmitter.Emit(vmList, rootNamespace));
        });
    }

    private static ViewModelValidationResult ExtractViewModelInfoWithValidation(GeneratorSyntaxContext context)
    {
        var diagnostics = ImmutableArray.CreateBuilder<Diagnostic>();
        var classDecl = (ClassDeclarationSyntax)context.Node;

        bool hasAttr = false;
        foreach (var attrList in classDecl.AttributeLists)
        {
            foreach (var attr in attrList.Attributes)
            {
                var name = attr.Name.ToString();
                if (name is "ViewModelAttribute" or "ViewModel")
                {
                    hasAttr = true;
                    break;
                }
            }
            if (hasAttr) break;
        }
        
        if (!hasAttr) 
            return new ViewModelValidationResult { Diagnostics = diagnostics.ToImmutable() };

        if (context.SemanticModel.GetDeclaredSymbol(context.Node) is not INamedTypeSymbol symbol)
            return new ViewModelValidationResult { Diagnostics = diagnostics.ToImmutable() };

        // VALIDATION: Check if class is declared as partial
        if (!classDecl.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword)))
        {
            diagnostics.Add(Diagnostic.Create(
                new DiagnosticDescriptor(
                    "VM001",
                    "ViewModel must be partial",
                    "[ViewModel] class '{0}' must be declared as 'partial'",
                    "SourceGenerator",
                    DiagnosticSeverity.Error,
                    isEnabledByDefault: true),
                classDecl.GetLocation(),
                symbol.Name));
            
            return new ViewModelValidationResult 
            { 
                Info = null,
                Diagnostics = diagnostics.ToImmutable()
            };
        }

        // Attribute symbols generated by this generator may not be fully bound on the first pass.
        // Capture syntax-marked members so [Observable]/[RelayCommand] are still discovered.
        var observableFieldNames = ImmutableHashSet.CreateBuilder<string>(StringComparer.Ordinal);
        var relayMethodNames = ImmutableHashSet.CreateBuilder<string>(StringComparer.Ordinal);

        foreach (var memberDecl in classDecl.Members)
        {
            if (memberDecl is FieldDeclarationSyntax fieldDecl && HasAttribute(fieldDecl, "Observable"))
            {
                foreach (var variable in fieldDecl.Declaration.Variables)
                {
                    observableFieldNames.Add(variable.Identifier.ValueText);
                }
            }

            if (memberDecl is MethodDeclarationSyntax methodDecl && HasAttribute(methodDecl, "RelayCommand"))
            {
                relayMethodNames.Add(methodDecl.Identifier.ValueText);
            }
        }

        var fields = ImmutableArray.CreateBuilder<ObservableFieldInfo>();
        var commands = ImmutableArray.CreateBuilder<RelayCommandInfo>();

        // Extract observable fields
        foreach (var member in symbol.GetMembers())
        {
            if (member is IFieldSymbol field &&
                (HasAttribute(field, "ObservableAttribute") || observableFieldNames.Contains(field.Name)))
            {
                var fieldName = field.Name;
                var propertyName = FieldToPropertyName(fieldName);
                var typeName = field.Type.ToDisplayString();
                var isNullable = field.Type.NullableAnnotation == NullableAnnotation.Annotated ||
                                 field.Type.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T;

                var notifyCommands = ImmutableArray.CreateBuilder<string>();
                var alsoNotify = ImmutableArray.CreateBuilder<string>();

                foreach (var attr in field.GetAttributes())
                {
                    if (attr.AttributeClass?.Name is "NotifyCanExecuteChangedAttribute" or "NotifyCanExecuteChanged")
                    {
                        foreach (var arg in attr.ConstructorArguments)
                        {
                            if (arg.Kind == TypedConstantKind.Array)
                            {
                                foreach (var item in arg.Values)
                                {
                                    if (item.Value is string s) notifyCommands.Add(s);
                                }
                            }
                            else if (arg.Value is string s)
                            {
                                notifyCommands.Add(s);
                            }
                        }
                    }
                    else if (attr.AttributeClass?.Name is "AlsoNotifyAttribute" or "AlsoNotify")
                    {
                        foreach (var arg in attr.ConstructorArguments)
                        {
                            if (arg.Kind == TypedConstantKind.Array)
                            {
                                foreach (var item in arg.Values)
                                {
                                    if (item.Value is string s) alsoNotify.Add(s);
                                }
                            }
                            else if (arg.Value is string s)
                            {
                                alsoNotify.Add(s);
                            }
                        }
                    }
                }

                fields.Add(new ObservableFieldInfo(
                    fieldName, propertyName, typeName, isNullable,
                    notifyCommands.ToImmutable(), alsoNotify.ToImmutable()));
            }

            // Extract relay commands
            if (member is IMethodSymbol method &&
                (HasAttribute(method, "RelayCommandAttribute") || relayMethodNames.Contains(method.Name)))
            {
                var methodName = method.Name;
                var commandName = MethodToCommandName(methodName);
                var returnType = method.ReturnType.ToDisplayString();
                var isAsync = returnType.Contains("Task");

                string? canExecute = null;
                foreach (var attr in method.GetAttributes())
                {
                    if (attr.AttributeClass?.Name is "RelayCommandAttribute" or "RelayCommand")
                    {
                        foreach (var na in attr.NamedArguments)
                        {
                            if (na.Key == "CanExecute" && na.Value.Value is string ce)
                                canExecute = ce;
                        }
                    }
                }

                // Determine parameter (excluding CancellationToken)
                bool hasParameter = false;
                string? parameterType = null;
                bool hasCt = false;

                foreach (var param in method.Parameters)
                {
                    if (param.Type.ToDisplayString().Contains("CancellationToken"))
                    {
                        hasCt = true;
                    }
                    else
                    {
                        hasParameter = true;
                        parameterType = param.Type.ToDisplayString();
                    }
                }

                commands.Add(new RelayCommandInfo(
                    methodName, commandName, canExecute, isAsync,
                    hasParameter, parameterType, hasCt));
            }
        }

        if (fields.Count == 0 && commands.Count == 0)
            return new ViewModelValidationResult { Diagnostics = diagnostics.ToImmutable() };

        var fieldsList = fields.ToImmutable();
        var commandsList = commands.ToImmutable();

        // VALIDATION: Check for duplicate observable field names
        var seenFieldNames = new HashSet<string>(StringComparer.Ordinal);
        foreach (var field in fieldsList)
        {
            if (!seenFieldNames.Add(field.PropertyName))
            {
                diagnostics.Add(Diagnostic.Create(
                    new DiagnosticDescriptor(
                        "VM002",
                        "Duplicate observable property",
                        "Observable property '{0}' is defined multiple times",
                        "SourceGenerator",
                        DiagnosticSeverity.Error,
                        isEnabledByDefault: true),
                    classDecl.GetLocation(),
                    field.PropertyName));
            }
        }

        // VALIDATION: Check for duplicate command names
        var seenCommandNames = new HashSet<string>(StringComparer.Ordinal);
        foreach (var cmd in commandsList)
        {
            if (!seenCommandNames.Add(cmd.CommandName))
            {
                diagnostics.Add(Diagnostic.Create(
                    new DiagnosticDescriptor(
                        "VM003",
                        "Duplicate relay command",
                        "Relay command '{0}' is defined multiple times",
                        "SourceGenerator",
                        DiagnosticSeverity.Error,
                        isEnabledByDefault: true),
                    classDecl.GetLocation(),
                    cmd.CommandName));
            }
        }

        // VALIDATION: Check if CanExecute methods exist
        foreach (var cmd in commandsList)
        {
            if (!string.IsNullOrEmpty(cmd.CanExecuteMethodName))
            {
                var canExecuteMethod = symbol.GetMembers(cmd.CanExecuteMethodName!)
                    .OfType<IMethodSymbol>()
                    .FirstOrDefault();

                if (canExecuteMethod is null)
                {
                    diagnostics.Add(Diagnostic.Create(
                        new DiagnosticDescriptor(
                            "VM004",
                            "CanExecute method not found",
                            "CanExecute method '{0}' referenced by '{1}' does not exist",
                            "SourceGenerator",
                            DiagnosticSeverity.Error,
                            isEnabledByDefault: true),
                        classDecl.GetLocation(),
                        cmd.CanExecuteMethodName,
                        cmd.CommandName));
                }
            }
        }

        var ns = symbol.ContainingNamespace.ToDisplayString();

        var info = new ViewModelInfo(
            symbol.ToDisplayString(),
            symbol.Name,
            ns,
            fieldsList,
            commandsList);

        return new ViewModelValidationResult
        {
            Info = diagnostics.Count > 0 ? null : info,
            Diagnostics = diagnostics.ToImmutable()
        };
    }

    private static string FieldToPropertyName(string fieldName)
    {
        // _title -> Title, _isLoading -> IsLoading, title -> Title
        if (fieldName.StartsWith("_") && fieldName.Length > 1)
            return char.ToUpperInvariant(fieldName[1]) + fieldName.Substring(2);

        return char.ToUpperInvariant(fieldName[0]) + fieldName.Substring(1);
    }

    private static string MethodToCommandName(string methodName)
    {
        // SaveAsync -> SaveCommand, Save -> SaveCommand
        var name = methodName;
        if (name.EndsWith("Async") && name.Length > 5)
            name = name.Substring(0, name.Length - 5);

        return name + "Command";
    }

    private static bool HasAttribute(ISymbol symbol, string attributeName)
    {
        return symbol.GetAttributes()
            .Any(a => a.AttributeClass?.Name == attributeName);
    }

    private static bool HasAttribute(MemberDeclarationSyntax member, string attributeName)
    {
        foreach (var attrList in member.AttributeLists)
        {
            foreach (var attr in attrList.Attributes)
            {
                var name = attr.Name.ToString();
                if (name == attributeName || name == attributeName + "Attribute")
                    return true;
            }
        }

        return false;
    }
}
